#ifndef KFASTBLOCK_COMMON_H
#define KFASTBLOCK_COMMON_H

#include <linux/types.h>

#define KFASTBLOCK_DRV_NAME "kfastblock"
#define KFASTBLOCK_DRV_NAME_PREFIX "kfb"
#define KFASTBLOCK_SYSFS_DEV_PREFIX "kfastblock-vol-"

#define KFASTBLOCK_DEVICE_PART_SHIFT 4
#define KFASTBLOCK_DEFAULT_BLOCK_SIZE 4096U
#define KFASTBLOCK_DEFAULT_OBJECT_SIZE (4U * 1024U * 1024U)
#define KFASTBLOCK_DEFAULT_QUEUE_DEPTH 128U
#define KFASTBLOCK_MAX_IO_BYTES (4U * 1024U * 1024U)
#define KFASTBLOCK_DEFAULT_MONITOR_PORT 3334U

#define KFASTBLOCK_MAX_NAME_LEN 128
#define KFASTBLOCK_MAX_ADDR_LEN 256
#define KFASTBLOCK_LAST_ERROR_LEN 256
#define KFASTBLOCK_MAX_MONITORS 8

#endif
