/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   msg__create_pool_request__init
                     (Msg__CreatePoolRequest         *message)
{
  static const Msg__CreatePoolRequest init_value = MSG__CREATE_POOL_REQUEST__INIT;
  *message = init_value;
}
size_t msg__create_pool_request__get_packed_size
                     (const Msg__CreatePoolRequest *message)
{
  assert(message->base.descriptor == &msg__create_pool_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__create_pool_request__pack
                     (const Msg__CreatePoolRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__create_pool_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__create_pool_request__pack_to_buffer
                     (const Msg__CreatePoolRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__create_pool_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__CreatePoolRequest *
       msg__create_pool_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__CreatePoolRequest *)
     protobuf_c_message_unpack (&msg__create_pool_request__descriptor,
                                allocator, len, data);
}
void   msg__create_pool_request__free_unpacked
                     (Msg__CreatePoolRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__create_pool_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__create_pool_response__init
                     (Msg__CreatePoolResponse         *message)
{
  static const Msg__CreatePoolResponse init_value = MSG__CREATE_POOL_RESPONSE__INIT;
  *message = init_value;
}
size_t msg__create_pool_response__get_packed_size
                     (const Msg__CreatePoolResponse *message)
{
  assert(message->base.descriptor == &msg__create_pool_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__create_pool_response__pack
                     (const Msg__CreatePoolResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__create_pool_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__create_pool_response__pack_to_buffer
                     (const Msg__CreatePoolResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__create_pool_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__CreatePoolResponse *
       msg__create_pool_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__CreatePoolResponse *)
     protobuf_c_message_unpack (&msg__create_pool_response__descriptor,
                                allocator, len, data);
}
void   msg__create_pool_response__free_unpacked
                     (Msg__CreatePoolResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__create_pool_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__delete_pool_request__init
                     (Msg__DeletePoolRequest         *message)
{
  static const Msg__DeletePoolRequest init_value = MSG__DELETE_POOL_REQUEST__INIT;
  *message = init_value;
}
size_t msg__delete_pool_request__get_packed_size
                     (const Msg__DeletePoolRequest *message)
{
  assert(message->base.descriptor == &msg__delete_pool_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__delete_pool_request__pack
                     (const Msg__DeletePoolRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__delete_pool_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__delete_pool_request__pack_to_buffer
                     (const Msg__DeletePoolRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__delete_pool_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__DeletePoolRequest *
       msg__delete_pool_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__DeletePoolRequest *)
     protobuf_c_message_unpack (&msg__delete_pool_request__descriptor,
                                allocator, len, data);
}
void   msg__delete_pool_request__free_unpacked
                     (Msg__DeletePoolRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__delete_pool_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__delete_pool_response__init
                     (Msg__DeletePoolResponse         *message)
{
  static const Msg__DeletePoolResponse init_value = MSG__DELETE_POOL_RESPONSE__INIT;
  *message = init_value;
}
size_t msg__delete_pool_response__get_packed_size
                     (const Msg__DeletePoolResponse *message)
{
  assert(message->base.descriptor == &msg__delete_pool_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__delete_pool_response__pack
                     (const Msg__DeletePoolResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__delete_pool_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__delete_pool_response__pack_to_buffer
                     (const Msg__DeletePoolResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__delete_pool_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__DeletePoolResponse *
       msg__delete_pool_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__DeletePoolResponse *)
     protobuf_c_message_unpack (&msg__delete_pool_response__descriptor,
                                allocator, len, data);
}
void   msg__delete_pool_response__free_unpacked
                     (Msg__DeletePoolResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__delete_pool_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__apply_idrequest__init
                     (Msg__ApplyIDRequest         *message)
{
  static const Msg__ApplyIDRequest init_value = MSG__APPLY_IDREQUEST__INIT;
  *message = init_value;
}
size_t msg__apply_idrequest__get_packed_size
                     (const Msg__ApplyIDRequest *message)
{
  assert(message->base.descriptor == &msg__apply_idrequest__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__apply_idrequest__pack
                     (const Msg__ApplyIDRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__apply_idrequest__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__apply_idrequest__pack_to_buffer
                     (const Msg__ApplyIDRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__apply_idrequest__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__ApplyIDRequest *
       msg__apply_idrequest__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__ApplyIDRequest *)
     protobuf_c_message_unpack (&msg__apply_idrequest__descriptor,
                                allocator, len, data);
}
void   msg__apply_idrequest__free_unpacked
                     (Msg__ApplyIDRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__apply_idrequest__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__apply_idresponse__init
                     (Msg__ApplyIDResponse         *message)
{
  static const Msg__ApplyIDResponse init_value = MSG__APPLY_IDRESPONSE__INIT;
  *message = init_value;
}
size_t msg__apply_idresponse__get_packed_size
                     (const Msg__ApplyIDResponse *message)
{
  assert(message->base.descriptor == &msg__apply_idresponse__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__apply_idresponse__pack
                     (const Msg__ApplyIDResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__apply_idresponse__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__apply_idresponse__pack_to_buffer
                     (const Msg__ApplyIDResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__apply_idresponse__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__ApplyIDResponse *
       msg__apply_idresponse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__ApplyIDResponse *)
     protobuf_c_message_unpack (&msg__apply_idresponse__descriptor,
                                allocator, len, data);
}
void   msg__apply_idresponse__free_unpacked
                     (Msg__ApplyIDResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__apply_idresponse__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__boot_request__init
                     (Msg__BootRequest         *message)
{
  static const Msg__BootRequest init_value = MSG__BOOT_REQUEST__INIT;
  *message = init_value;
}
size_t msg__boot_request__get_packed_size
                     (const Msg__BootRequest *message)
{
  assert(message->base.descriptor == &msg__boot_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__boot_request__pack
                     (const Msg__BootRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__boot_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__boot_request__pack_to_buffer
                     (const Msg__BootRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__boot_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__BootRequest *
       msg__boot_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__BootRequest *)
     protobuf_c_message_unpack (&msg__boot_request__descriptor,
                                allocator, len, data);
}
void   msg__boot_request__free_unpacked
                     (Msg__BootRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__boot_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__boot_response__init
                     (Msg__BootResponse         *message)
{
  static const Msg__BootResponse init_value = MSG__BOOT_RESPONSE__INIT;
  *message = init_value;
}
size_t msg__boot_response__get_packed_size
                     (const Msg__BootResponse *message)
{
  assert(message->base.descriptor == &msg__boot_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__boot_response__pack
                     (const Msg__BootResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__boot_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__boot_response__pack_to_buffer
                     (const Msg__BootResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__boot_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__BootResponse *
       msg__boot_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__BootResponse *)
     protobuf_c_message_unpack (&msg__boot_response__descriptor,
                                allocator, len, data);
}
void   msg__boot_response__free_unpacked
                     (Msg__BootResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__boot_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__stop_request__init
                     (Msg__StopRequest         *message)
{
  static const Msg__StopRequest init_value = MSG__STOP_REQUEST__INIT;
  *message = init_value;
}
size_t msg__stop_request__get_packed_size
                     (const Msg__StopRequest *message)
{
  assert(message->base.descriptor == &msg__stop_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__stop_request__pack
                     (const Msg__StopRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__stop_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__stop_request__pack_to_buffer
                     (const Msg__StopRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__stop_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__StopRequest *
       msg__stop_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__StopRequest *)
     protobuf_c_message_unpack (&msg__stop_request__descriptor,
                                allocator, len, data);
}
void   msg__stop_request__free_unpacked
                     (Msg__StopRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__stop_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__stop_response__init
                     (Msg__StopResponse         *message)
{
  static const Msg__StopResponse init_value = MSG__STOP_RESPONSE__INIT;
  *message = init_value;
}
size_t msg__stop_response__get_packed_size
                     (const Msg__StopResponse *message)
{
  assert(message->base.descriptor == &msg__stop_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__stop_response__pack
                     (const Msg__StopResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__stop_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__stop_response__pack_to_buffer
                     (const Msg__StopResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__stop_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__StopResponse *
       msg__stop_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__StopResponse *)
     protobuf_c_message_unpack (&msg__stop_response__descriptor,
                                allocator, len, data);
}
void   msg__stop_response__free_unpacked
                     (Msg__StopResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__stop_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__heartbeat_request__init
                     (Msg__HeartbeatRequest         *message)
{
  static const Msg__HeartbeatRequest init_value = MSG__HEARTBEAT_REQUEST__INIT;
  *message = init_value;
}
size_t msg__heartbeat_request__get_packed_size
                     (const Msg__HeartbeatRequest *message)
{
  assert(message->base.descriptor == &msg__heartbeat_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__heartbeat_request__pack
                     (const Msg__HeartbeatRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__heartbeat_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__heartbeat_request__pack_to_buffer
                     (const Msg__HeartbeatRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__heartbeat_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__HeartbeatRequest *
       msg__heartbeat_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__HeartbeatRequest *)
     protobuf_c_message_unpack (&msg__heartbeat_request__descriptor,
                                allocator, len, data);
}
void   msg__heartbeat_request__free_unpacked
                     (Msg__HeartbeatRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__heartbeat_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__heartbeat_response__init
                     (Msg__HeartbeatResponse         *message)
{
  static const Msg__HeartbeatResponse init_value = MSG__HEARTBEAT_RESPONSE__INIT;
  *message = init_value;
}
size_t msg__heartbeat_response__get_packed_size
                     (const Msg__HeartbeatResponse *message)
{
  assert(message->base.descriptor == &msg__heartbeat_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__heartbeat_response__pack
                     (const Msg__HeartbeatResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__heartbeat_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__heartbeat_response__pack_to_buffer
                     (const Msg__HeartbeatResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__heartbeat_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__HeartbeatResponse *
       msg__heartbeat_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__HeartbeatResponse *)
     protobuf_c_message_unpack (&msg__heartbeat_response__descriptor,
                                allocator, len, data);
}
void   msg__heartbeat_response__free_unpacked
                     (Msg__HeartbeatResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__heartbeat_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__create_pgrequest__init
                     (Msg__CreatePGRequest         *message)
{
  static const Msg__CreatePGRequest init_value = MSG__CREATE_PGREQUEST__INIT;
  *message = init_value;
}
size_t msg__create_pgrequest__get_packed_size
                     (const Msg__CreatePGRequest *message)
{
  assert(message->base.descriptor == &msg__create_pgrequest__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__create_pgrequest__pack
                     (const Msg__CreatePGRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__create_pgrequest__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__create_pgrequest__pack_to_buffer
                     (const Msg__CreatePGRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__create_pgrequest__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__CreatePGRequest *
       msg__create_pgrequest__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__CreatePGRequest *)
     protobuf_c_message_unpack (&msg__create_pgrequest__descriptor,
                                allocator, len, data);
}
void   msg__create_pgrequest__free_unpacked
                     (Msg__CreatePGRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__create_pgrequest__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__create_pgresponse__init
                     (Msg__CreatePGResponse         *message)
{
  static const Msg__CreatePGResponse init_value = MSG__CREATE_PGRESPONSE__INIT;
  *message = init_value;
}
size_t msg__create_pgresponse__get_packed_size
                     (const Msg__CreatePGResponse *message)
{
  assert(message->base.descriptor == &msg__create_pgresponse__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__create_pgresponse__pack
                     (const Msg__CreatePGResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__create_pgresponse__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__create_pgresponse__pack_to_buffer
                     (const Msg__CreatePGResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__create_pgresponse__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__CreatePGResponse *
       msg__create_pgresponse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__CreatePGResponse *)
     protobuf_c_message_unpack (&msg__create_pgresponse__descriptor,
                                allocator, len, data);
}
void   msg__create_pgresponse__free_unpacked
                     (Msg__CreatePGResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__create_pgresponse__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__delete_pgrequest__init
                     (Msg__DeletePGRequest         *message)
{
  static const Msg__DeletePGRequest init_value = MSG__DELETE_PGREQUEST__INIT;
  *message = init_value;
}
size_t msg__delete_pgrequest__get_packed_size
                     (const Msg__DeletePGRequest *message)
{
  assert(message->base.descriptor == &msg__delete_pgrequest__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__delete_pgrequest__pack
                     (const Msg__DeletePGRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__delete_pgrequest__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__delete_pgrequest__pack_to_buffer
                     (const Msg__DeletePGRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__delete_pgrequest__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__DeletePGRequest *
       msg__delete_pgrequest__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__DeletePGRequest *)
     protobuf_c_message_unpack (&msg__delete_pgrequest__descriptor,
                                allocator, len, data);
}
void   msg__delete_pgrequest__free_unpacked
                     (Msg__DeletePGRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__delete_pgrequest__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__delete_pgresponse__init
                     (Msg__DeletePGResponse         *message)
{
  static const Msg__DeletePGResponse init_value = MSG__DELETE_PGRESPONSE__INIT;
  *message = init_value;
}
size_t msg__delete_pgresponse__get_packed_size
                     (const Msg__DeletePGResponse *message)
{
  assert(message->base.descriptor == &msg__delete_pgresponse__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__delete_pgresponse__pack
                     (const Msg__DeletePGResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__delete_pgresponse__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__delete_pgresponse__pack_to_buffer
                     (const Msg__DeletePGResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__delete_pgresponse__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__DeletePGResponse *
       msg__delete_pgresponse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__DeletePGResponse *)
     protobuf_c_message_unpack (&msg__delete_pgresponse__descriptor,
                                allocator, len, data);
}
void   msg__delete_pgresponse__free_unpacked
                     (Msg__DeletePGResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__delete_pgresponse__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__request__init
                     (Msg__Request         *message)
{
  static const Msg__Request init_value = MSG__REQUEST__INIT;
  *message = init_value;
}
size_t msg__request__get_packed_size
                     (const Msg__Request *message)
{
  assert(message->base.descriptor == &msg__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__request__pack
                     (const Msg__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__request__pack_to_buffer
                     (const Msg__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__Request *
       msg__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__Request *)
     protobuf_c_message_unpack (&msg__request__descriptor,
                                allocator, len, data);
}
void   msg__request__free_unpacked
                     (Msg__Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__response__init
                     (Msg__Response         *message)
{
  static const Msg__Response init_value = MSG__RESPONSE__INIT;
  *message = init_value;
}
size_t msg__response__get_packed_size
                     (const Msg__Response *message)
{
  assert(message->base.descriptor == &msg__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__response__pack
                     (const Msg__Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__response__pack_to_buffer
                     (const Msg__Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__Response *
       msg__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__Response *)
     protobuf_c_message_unpack (&msg__response__descriptor,
                                allocator, len, data);
}
void   msg__response__free_unpacked
                     (Msg__Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor msg__create_pool_request__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__CreatePoolRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pgsize",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__CreatePoolRequest, pgsize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pgcount",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__CreatePoolRequest, pgcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "failuredomain",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__CreatePoolRequest, failuredomain),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "root",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__CreatePoolRequest, root),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__create_pool_request__field_indices_by_name[] = {
  3,   /* field[3] = failuredomain */
  0,   /* field[0] = name */
  2,   /* field[2] = pgcount */
  1,   /* field[1] = pgsize */
  4,   /* field[4] = root */
};
static const ProtobufCIntRange msg__create_pool_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor msg__create_pool_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.CreatePoolRequest",
  "CreatePoolRequest",
  "Msg__CreatePoolRequest",
  "msg",
  sizeof(Msg__CreatePoolRequest),
  5,
  msg__create_pool_request__field_descriptors,
  msg__create_pool_request__field_indices_by_name,
  1,  msg__create_pool_request__number_ranges,
  (ProtobufCMessageInit) msg__create_pool_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__create_pool_response__field_descriptors[2] =
{
  {
    "ok",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Msg__CreatePoolResponse, ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "poolid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__CreatePoolResponse, poolid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__create_pool_response__field_indices_by_name[] = {
  0,   /* field[0] = ok */
  1,   /* field[1] = poolid */
};
static const ProtobufCIntRange msg__create_pool_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor msg__create_pool_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.CreatePoolResponse",
  "CreatePoolResponse",
  "Msg__CreatePoolResponse",
  "msg",
  sizeof(Msg__CreatePoolResponse),
  2,
  msg__create_pool_response__field_descriptors,
  msg__create_pool_response__field_indices_by_name,
  1,  msg__create_pool_response__number_ranges,
  (ProtobufCMessageInit) msg__create_pool_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__delete_pool_request__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__DeletePoolRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__delete_pool_request__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange msg__delete_pool_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg__delete_pool_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.DeletePoolRequest",
  "DeletePoolRequest",
  "Msg__DeletePoolRequest",
  "msg",
  sizeof(Msg__DeletePoolRequest),
  1,
  msg__delete_pool_request__field_descriptors,
  msg__delete_pool_request__field_indices_by_name,
  1,  msg__delete_pool_request__number_ranges,
  (ProtobufCMessageInit) msg__delete_pool_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__delete_pool_response__field_descriptors[1] =
{
  {
    "ok",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Msg__DeletePoolResponse, ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__delete_pool_response__field_indices_by_name[] = {
  0,   /* field[0] = ok */
};
static const ProtobufCIntRange msg__delete_pool_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg__delete_pool_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.DeletePoolResponse",
  "DeletePoolResponse",
  "Msg__DeletePoolResponse",
  "msg",
  sizeof(Msg__DeletePoolResponse),
  1,
  msg__delete_pool_response__field_descriptors,
  msg__delete_pool_response__field_indices_by_name,
  1,  msg__delete_pool_response__number_ranges,
  (ProtobufCMessageInit) msg__delete_pool_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__apply_idrequest__field_descriptors[1] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ApplyIDRequest, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__apply_idrequest__field_indices_by_name[] = {
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange msg__apply_idrequest__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg__apply_idrequest__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.ApplyIDRequest",
  "ApplyIDRequest",
  "Msg__ApplyIDRequest",
  "msg",
  sizeof(Msg__ApplyIDRequest),
  1,
  msg__apply_idrequest__field_descriptors,
  msg__apply_idrequest__field_indices_by_name,
  1,  msg__apply_idrequest__number_ranges,
  (ProtobufCMessageInit) msg__apply_idrequest__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__apply_idresponse__field_descriptors[2] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ApplyIDResponse, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__ApplyIDResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__apply_idresponse__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange msg__apply_idresponse__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor msg__apply_idresponse__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.ApplyIDResponse",
  "ApplyIDResponse",
  "Msg__ApplyIDResponse",
  "msg",
  sizeof(Msg__ApplyIDResponse),
  2,
  msg__apply_idresponse__field_descriptors,
  msg__apply_idresponse__field_indices_by_name,
  1,  msg__apply_idresponse__number_ranges,
  (ProtobufCMessageInit) msg__apply_idresponse__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__boot_request__field_descriptors[6] =
{
  {
    "osd_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__BootRequest, osd_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__BootRequest, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__BootRequest, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Msg__BootRequest, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__BootRequest, address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__BootRequest, host),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__boot_request__field_indices_by_name[] = {
  4,   /* field[4] = address */
  5,   /* field[5] = host */
  0,   /* field[0] = osd_id */
  3,   /* field[3] = port */
  2,   /* field[2] = size */
  1,   /* field[1] = uuid */
};
static const ProtobufCIntRange msg__boot_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor msg__boot_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.BootRequest",
  "BootRequest",
  "Msg__BootRequest",
  "msg",
  sizeof(Msg__BootRequest),
  6,
  msg__boot_request__field_descriptors,
  msg__boot_request__field_indices_by_name,
  1,  msg__boot_request__number_ranges,
  (ProtobufCMessageInit) msg__boot_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__boot_response__field_descriptors[1] =
{
  {
    "ok",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Msg__BootResponse, ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__boot_response__field_indices_by_name[] = {
  0,   /* field[0] = ok */
};
static const ProtobufCIntRange msg__boot_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg__boot_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.BootResponse",
  "BootResponse",
  "Msg__BootResponse",
  "msg",
  sizeof(Msg__BootResponse),
  1,
  msg__boot_response__field_descriptors,
  msg__boot_response__field_indices_by_name,
  1,  msg__boot_response__number_ranges,
  (ProtobufCMessageInit) msg__boot_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__stop_request__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__StopRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__stop_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange msg__stop_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg__stop_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.StopRequest",
  "StopRequest",
  "Msg__StopRequest",
  "msg",
  sizeof(Msg__StopRequest),
  1,
  msg__stop_request__field_descriptors,
  msg__stop_request__field_indices_by_name,
  1,  msg__stop_request__number_ranges,
  (ProtobufCMessageInit) msg__stop_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__stop_response__field_descriptors[1] =
{
  {
    "ok",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Msg__StopResponse, ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__stop_response__field_indices_by_name[] = {
  0,   /* field[0] = ok */
};
static const ProtobufCIntRange msg__stop_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg__stop_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.StopResponse",
  "StopResponse",
  "Msg__StopResponse",
  "msg",
  sizeof(Msg__StopResponse),
  1,
  msg__stop_response__field_descriptors,
  msg__stop_response__field_indices_by_name,
  1,  msg__stop_response__number_ranges,
  (ProtobufCMessageInit) msg__stop_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__heartbeat_request__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__HeartbeatRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__heartbeat_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange msg__heartbeat_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg__heartbeat_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.HeartbeatRequest",
  "HeartbeatRequest",
  "Msg__HeartbeatRequest",
  "msg",
  sizeof(Msg__HeartbeatRequest),
  1,
  msg__heartbeat_request__field_descriptors,
  msg__heartbeat_request__field_indices_by_name,
  1,  msg__heartbeat_request__number_ranges,
  (ProtobufCMessageInit) msg__heartbeat_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__heartbeat_response__field_descriptors[1] =
{
  {
    "ok",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Msg__HeartbeatResponse, ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__heartbeat_response__field_indices_by_name[] = {
  0,   /* field[0] = ok */
};
static const ProtobufCIntRange msg__heartbeat_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg__heartbeat_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.HeartbeatResponse",
  "HeartbeatResponse",
  "Msg__HeartbeatResponse",
  "msg",
  sizeof(Msg__HeartbeatResponse),
  1,
  msg__heartbeat_response__field_descriptors,
  msg__heartbeat_response__field_indices_by_name,
  1,  msg__heartbeat_response__number_ranges,
  (ProtobufCMessageInit) msg__heartbeat_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__create_pgrequest__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__CreatePGRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pgid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__CreatePGRequest, pgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "other_osd1",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__CreatePGRequest, other_osd1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "other_osd2",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__CreatePGRequest, other_osd2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__create_pgrequest__field_indices_by_name[] = {
  0,   /* field[0] = id */
  2,   /* field[2] = other_osd1 */
  3,   /* field[3] = other_osd2 */
  1,   /* field[1] = pgid */
};
static const ProtobufCIntRange msg__create_pgrequest__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor msg__create_pgrequest__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.CreatePGRequest",
  "CreatePGRequest",
  "Msg__CreatePGRequest",
  "msg",
  sizeof(Msg__CreatePGRequest),
  4,
  msg__create_pgrequest__field_descriptors,
  msg__create_pgrequest__field_indices_by_name,
  1,  msg__create_pgrequest__number_ranges,
  (ProtobufCMessageInit) msg__create_pgrequest__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__create_pgresponse__field_descriptors[1] =
{
  {
    "ok",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Msg__CreatePGResponse, ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__create_pgresponse__field_indices_by_name[] = {
  0,   /* field[0] = ok */
};
static const ProtobufCIntRange msg__create_pgresponse__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg__create_pgresponse__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.CreatePGResponse",
  "CreatePGResponse",
  "Msg__CreatePGResponse",
  "msg",
  sizeof(Msg__CreatePGResponse),
  1,
  msg__create_pgresponse__field_descriptors,
  msg__create_pgresponse__field_indices_by_name,
  1,  msg__create_pgresponse__number_ranges,
  (ProtobufCMessageInit) msg__create_pgresponse__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__delete_pgrequest__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__DeletePGRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pgid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__DeletePGRequest, pgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__delete_pgrequest__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = pgid */
};
static const ProtobufCIntRange msg__delete_pgrequest__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor msg__delete_pgrequest__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.DeletePGRequest",
  "DeletePGRequest",
  "Msg__DeletePGRequest",
  "msg",
  sizeof(Msg__DeletePGRequest),
  2,
  msg__delete_pgrequest__field_descriptors,
  msg__delete_pgrequest__field_indices_by_name,
  1,  msg__delete_pgrequest__number_ranges,
  (ProtobufCMessageInit) msg__delete_pgrequest__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__delete_pgresponse__field_descriptors[1] =
{
  {
    "ok",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Msg__DeletePGResponse, ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__delete_pgresponse__field_indices_by_name[] = {
  0,   /* field[0] = ok */
};
static const ProtobufCIntRange msg__delete_pgresponse__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg__delete_pgresponse__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.DeletePGResponse",
  "DeletePGResponse",
  "Msg__DeletePGResponse",
  "msg",
  sizeof(Msg__DeletePGResponse),
  1,
  msg__delete_pgresponse__field_descriptors,
  msg__delete_pgresponse__field_indices_by_name,
  1,  msg__delete_pgresponse__number_ranges,
  (ProtobufCMessageInit) msg__delete_pgresponse__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__request__field_descriptors[7] =
{
  {
    "boot_request",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Request, union_case),
    offsetof(Msg__Request, boot_request),
    &msg__boot_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop_request",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Request, union_case),
    offsetof(Msg__Request, stop_request),
    &msg__stop_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heartbeat_request",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Request, union_case),
    offsetof(Msg__Request, heartbeat_request),
    &msg__heartbeat_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_pg_request",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Request, union_case),
    offsetof(Msg__Request, create_pg_request),
    &msg__create_pgrequest__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete_pg_request",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Request, union_case),
    offsetof(Msg__Request, delete_pg_request),
    &msg__delete_pgrequest__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "apply_id_request",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Request, union_case),
    offsetof(Msg__Request, apply_id_request),
    &msg__apply_idrequest__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_pool_request",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Request, union_case),
    offsetof(Msg__Request, create_pool_request),
    &msg__create_pool_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__request__field_indices_by_name[] = {
  5,   /* field[5] = apply_id_request */
  0,   /* field[0] = boot_request */
  3,   /* field[3] = create_pg_request */
  6,   /* field[6] = create_pool_request */
  4,   /* field[4] = delete_pg_request */
  2,   /* field[2] = heartbeat_request */
  1,   /* field[1] = stop_request */
};
static const ProtobufCIntRange msg__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor msg__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.Request",
  "Request",
  "Msg__Request",
  "msg",
  sizeof(Msg__Request),
  7,
  msg__request__field_descriptors,
  msg__request__field_indices_by_name,
  1,  msg__request__number_ranges,
  (ProtobufCMessageInit) msg__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__response__field_descriptors[7] =
{
  {
    "boot_response",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Response, union_case),
    offsetof(Msg__Response, boot_response),
    &msg__boot_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop_response",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Response, union_case),
    offsetof(Msg__Response, stop_response),
    &msg__stop_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heartbeat_response",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Response, union_case),
    offsetof(Msg__Response, heartbeat_response),
    &msg__heartbeat_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_pg_response",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Response, union_case),
    offsetof(Msg__Response, create_pg_response),
    &msg__create_pgresponse__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete_pg_response",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Response, union_case),
    offsetof(Msg__Response, delete_pg_response),
    &msg__delete_pgresponse__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "apply_id_response",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Response, union_case),
    offsetof(Msg__Response, apply_id_response),
    &msg__apply_idresponse__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_pool_response",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__Response, union_case),
    offsetof(Msg__Response, create_pool_response),
    &msg__create_pool_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__response__field_indices_by_name[] = {
  5,   /* field[5] = apply_id_response */
  0,   /* field[0] = boot_response */
  3,   /* field[3] = create_pg_response */
  6,   /* field[6] = create_pool_response */
  4,   /* field[4] = delete_pg_response */
  2,   /* field[2] = heartbeat_response */
  1,   /* field[1] = stop_response */
};
static const ProtobufCIntRange msg__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor msg__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.Response",
  "Response",
  "Msg__Response",
  "msg",
  sizeof(Msg__Response),
  7,
  msg__response__field_descriptors,
  msg__response__field_indices_by_name,
  1,  msg__response__number_ranges,
  (ProtobufCMessageInit) msg__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
