// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: messages.proto

package msg

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetPgMapErrorCode int32

const (
	GetPgMapErrorCode_pgMapGetOk               GetPgMapErrorCode = 0
	GetPgMapErrorCode_pgMapclientVersionHigher GetPgMapErrorCode = 1
	GetPgMapErrorCode_PgMapclusterNoPools      GetPgMapErrorCode = 2
	GetPgMapErrorCode_PgMapSameVersion         GetPgMapErrorCode = 3
)

var GetPgMapErrorCode_name = map[int32]string{
	0: "pgMapGetOk",
	1: "pgMapclientVersionHigher",
	2: "PgMapclusterNoPools",
	3: "PgMapSameVersion",
}

var GetPgMapErrorCode_value = map[string]int32{
	"pgMapGetOk":               0,
	"pgMapclientVersionHigher": 1,
	"PgMapclusterNoPools":      2,
	"PgMapSameVersion":         3,
}

func (x GetPgMapErrorCode) String() string {
	return proto.EnumName(GetPgMapErrorCode_name, int32(x))
}

func (GetPgMapErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

type OsdMapErrorCode int32

const (
	OsdMapErrorCode_ok                   OsdMapErrorCode = 0
	OsdMapErrorCode_clientVersionHigher  OsdMapErrorCode = 1
	OsdMapErrorCode_clientVersionInvalid OsdMapErrorCode = 2
	OsdMapErrorCode_noOsdsExist          OsdMapErrorCode = 3
)

var OsdMapErrorCode_name = map[int32]string{
	0: "ok",
	1: "clientVersionHigher",
	2: "clientVersionInvalid",
	3: "noOsdsExist",
}

var OsdMapErrorCode_value = map[string]int32{
	"ok":                   0,
	"clientVersionHigher":  1,
	"clientVersionInvalid": 2,
	"noOsdsExist":          3,
}

func (x OsdMapErrorCode) String() string {
	return proto.EnumName(OsdMapErrorCode_name, int32(x))
}

func (OsdMapErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

type CreateImageErrorCode int32

const (
	CreateImageErrorCode_createImageOk            CreateImageErrorCode = 0
	CreateImageErrorCode_imageExists              CreateImageErrorCode = 1
	CreateImageErrorCode_unknownPoolName          CreateImageErrorCode = 2
	CreateImageErrorCode_marshalImageContextError CreateImageErrorCode = 3
	CreateImageErrorCode_putEtcdError             CreateImageErrorCode = 4
)

var CreateImageErrorCode_name = map[int32]string{
	0: "createImageOk",
	1: "imageExists",
	2: "unknownPoolName",
	3: "marshalImageContextError",
	4: "putEtcdError",
}

var CreateImageErrorCode_value = map[string]int32{
	"createImageOk":            0,
	"imageExists":              1,
	"unknownPoolName":          2,
	"marshalImageContextError": 3,
	"putEtcdError":             4,
}

func (x CreateImageErrorCode) String() string {
	return proto.EnumName(CreateImageErrorCode_name, int32(x))
}

func (CreateImageErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

type RemoveImageErrorCode int32

const (
	RemoveImageErrorCode_removeImageOk   RemoveImageErrorCode = 0
	RemoveImageErrorCode_imageNotFound   RemoveImageErrorCode = 1
	RemoveImageErrorCode_removeImageFail RemoveImageErrorCode = 2
)

var RemoveImageErrorCode_name = map[int32]string{
	0: "removeImageOk",
	1: "imageNotFound",
	2: "removeImageFail",
}

var RemoveImageErrorCode_value = map[string]int32{
	"removeImageOk":   0,
	"imageNotFound":   1,
	"removeImageFail": 2,
}

func (x RemoveImageErrorCode) String() string {
	return proto.EnumName(RemoveImageErrorCode_name, int32(x))
}

func (RemoveImageErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

type ResizeImageErrorCode int32

const (
	ResizeImageErrorCode_resizeImageOk                  ResizeImageErrorCode = 0
	ResizeImageErrorCode_resizeImageNotFound            ResizeImageErrorCode = 1
	ResizeImageErrorCode_marshalResizeImageContextError ResizeImageErrorCode = 2
	ResizeImageErrorCode_putResizeImageEtcdError        ResizeImageErrorCode = 3
)

var ResizeImageErrorCode_name = map[int32]string{
	0: "resizeImageOk",
	1: "resizeImageNotFound",
	2: "marshalResizeImageContextError",
	3: "putResizeImageEtcdError",
}

var ResizeImageErrorCode_value = map[string]int32{
	"resizeImageOk":                  0,
	"resizeImageNotFound":            1,
	"marshalResizeImageContextError": 2,
	"putResizeImageEtcdError":        3,
}

func (x ResizeImageErrorCode) String() string {
	return proto.EnumName(ResizeImageErrorCode_name, int32(x))
}

func (ResizeImageErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

type GetImageErrorCode int32

const (
	GetImageErrorCode_getImageOk       GetImageErrorCode = 0
	GetImageErrorCode_getImageNotFound GetImageErrorCode = 1
)

var GetImageErrorCode_name = map[int32]string{
	0: "getImageOk",
	1: "getImageNotFound",
}

var GetImageErrorCode_value = map[string]int32{
	"getImageOk":       0,
	"getImageNotFound": 1,
}

func (x GetImageErrorCode) String() string {
	return proto.EnumName(GetImageErrorCode_name, int32(x))
}

func (GetImageErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

type CreatePoolRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pgsize               int32    `protobuf:"varint,2,opt,name=pgsize,proto3" json:"pgsize,omitempty"`
	Pgcount              int32    `protobuf:"varint,3,opt,name=pgcount,proto3" json:"pgcount,omitempty"`
	Failuredomain        string   `protobuf:"bytes,4,opt,name=failuredomain,proto3" json:"failuredomain,omitempty"`
	Root                 string   `protobuf:"bytes,5,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePoolRequest) Reset()         { *m = CreatePoolRequest{} }
func (m *CreatePoolRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePoolRequest) ProtoMessage()    {}
func (*CreatePoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}
func (m *CreatePoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePoolRequest.Unmarshal(m, b)
}
func (m *CreatePoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePoolRequest.Marshal(b, m, deterministic)
}
func (m *CreatePoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePoolRequest.Merge(m, src)
}
func (m *CreatePoolRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePoolRequest.Size(m)
}
func (m *CreatePoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePoolRequest proto.InternalMessageInfo

func (m *CreatePoolRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePoolRequest) GetPgsize() int32 {
	if m != nil {
		return m.Pgsize
	}
	return 0
}

func (m *CreatePoolRequest) GetPgcount() int32 {
	if m != nil {
		return m.Pgcount
	}
	return 0
}

func (m *CreatePoolRequest) GetFailuredomain() string {
	if m != nil {
		return m.Failuredomain
	}
	return ""
}

func (m *CreatePoolRequest) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

type CreatePoolResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Poolid               int32    `protobuf:"varint,2,opt,name=poolid,proto3" json:"poolid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePoolResponse) Reset()         { *m = CreatePoolResponse{} }
func (m *CreatePoolResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePoolResponse) ProtoMessage()    {}
func (*CreatePoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}
func (m *CreatePoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePoolResponse.Unmarshal(m, b)
}
func (m *CreatePoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePoolResponse.Marshal(b, m, deterministic)
}
func (m *CreatePoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePoolResponse.Merge(m, src)
}
func (m *CreatePoolResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePoolResponse.Size(m)
}
func (m *CreatePoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePoolResponse proto.InternalMessageInfo

func (m *CreatePoolResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *CreatePoolResponse) GetPoolid() int32 {
	if m != nil {
		return m.Poolid
	}
	return 0
}

type ListPoolsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPoolsRequest) Reset()         { *m = ListPoolsRequest{} }
func (m *ListPoolsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPoolsRequest) ProtoMessage()    {}
func (*ListPoolsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}
func (m *ListPoolsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoolsRequest.Unmarshal(m, b)
}
func (m *ListPoolsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoolsRequest.Marshal(b, m, deterministic)
}
func (m *ListPoolsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoolsRequest.Merge(m, src)
}
func (m *ListPoolsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPoolsRequest.Size(m)
}
func (m *ListPoolsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoolsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoolsRequest proto.InternalMessageInfo

type Poolinfo struct {
	Poolid               int32    `protobuf:"varint,1,opt,name=poolid,proto3" json:"poolid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pgsize               int32    `protobuf:"varint,3,opt,name=pgsize,proto3" json:"pgsize,omitempty"`
	Pgcount              int32    `protobuf:"varint,4,opt,name=pgcount,proto3" json:"pgcount,omitempty"`
	Failuredomain        string   `protobuf:"bytes,5,opt,name=failuredomain,proto3" json:"failuredomain,omitempty"`
	Root                 string   `protobuf:"bytes,6,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Poolinfo) Reset()         { *m = Poolinfo{} }
func (m *Poolinfo) String() string { return proto.CompactTextString(m) }
func (*Poolinfo) ProtoMessage()    {}
func (*Poolinfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}
func (m *Poolinfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Poolinfo.Unmarshal(m, b)
}
func (m *Poolinfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Poolinfo.Marshal(b, m, deterministic)
}
func (m *Poolinfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poolinfo.Merge(m, src)
}
func (m *Poolinfo) XXX_Size() int {
	return xxx_messageInfo_Poolinfo.Size(m)
}
func (m *Poolinfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Poolinfo.DiscardUnknown(m)
}

var xxx_messageInfo_Poolinfo proto.InternalMessageInfo

func (m *Poolinfo) GetPoolid() int32 {
	if m != nil {
		return m.Poolid
	}
	return 0
}

func (m *Poolinfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Poolinfo) GetPgsize() int32 {
	if m != nil {
		return m.Pgsize
	}
	return 0
}

func (m *Poolinfo) GetPgcount() int32 {
	if m != nil {
		return m.Pgcount
	}
	return 0
}

func (m *Poolinfo) GetFailuredomain() string {
	if m != nil {
		return m.Failuredomain
	}
	return ""
}

func (m *Poolinfo) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

type ListPoolsResponse struct {
	Pi                   []*Poolinfo `protobuf:"bytes,1,rep,name=pi,proto3" json:"pi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListPoolsResponse) Reset()         { *m = ListPoolsResponse{} }
func (m *ListPoolsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPoolsResponse) ProtoMessage()    {}
func (*ListPoolsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}
func (m *ListPoolsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoolsResponse.Unmarshal(m, b)
}
func (m *ListPoolsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoolsResponse.Marshal(b, m, deterministic)
}
func (m *ListPoolsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoolsResponse.Merge(m, src)
}
func (m *ListPoolsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPoolsResponse.Size(m)
}
func (m *ListPoolsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoolsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoolsResponse proto.InternalMessageInfo

func (m *ListPoolsResponse) GetPi() []*Poolinfo {
	if m != nil {
		return m.Pi
	}
	return nil
}

type DeletePoolRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePoolRequest) Reset()         { *m = DeletePoolRequest{} }
func (m *DeletePoolRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePoolRequest) ProtoMessage()    {}
func (*DeletePoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}
func (m *DeletePoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePoolRequest.Unmarshal(m, b)
}
func (m *DeletePoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePoolRequest.Marshal(b, m, deterministic)
}
func (m *DeletePoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePoolRequest.Merge(m, src)
}
func (m *DeletePoolRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePoolRequest.Size(m)
}
func (m *DeletePoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePoolRequest proto.InternalMessageInfo

func (m *DeletePoolRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeletePoolResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePoolResponse) Reset()         { *m = DeletePoolResponse{} }
func (m *DeletePoolResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePoolResponse) ProtoMessage()    {}
func (*DeletePoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}
func (m *DeletePoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePoolResponse.Unmarshal(m, b)
}
func (m *DeletePoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePoolResponse.Marshal(b, m, deterministic)
}
func (m *DeletePoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePoolResponse.Merge(m, src)
}
func (m *DeletePoolResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePoolResponse.Size(m)
}
func (m *DeletePoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePoolResponse proto.InternalMessageInfo

func (m *DeletePoolResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ApplyIDRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyIDRequest) Reset()         { *m = ApplyIDRequest{} }
func (m *ApplyIDRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyIDRequest) ProtoMessage()    {}
func (*ApplyIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{7}
}
func (m *ApplyIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyIDRequest.Unmarshal(m, b)
}
func (m *ApplyIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyIDRequest.Marshal(b, m, deterministic)
}
func (m *ApplyIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyIDRequest.Merge(m, src)
}
func (m *ApplyIDRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyIDRequest.Size(m)
}
func (m *ApplyIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyIDRequest proto.InternalMessageInfo

func (m *ApplyIDRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type ApplyIDResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyIDResponse) Reset()         { *m = ApplyIDResponse{} }
func (m *ApplyIDResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyIDResponse) ProtoMessage()    {}
func (*ApplyIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{8}
}
func (m *ApplyIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyIDResponse.Unmarshal(m, b)
}
func (m *ApplyIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyIDResponse.Marshal(b, m, deterministic)
}
func (m *ApplyIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyIDResponse.Merge(m, src)
}
func (m *ApplyIDResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyIDResponse.Size(m)
}
func (m *ApplyIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyIDResponse proto.InternalMessageInfo

func (m *ApplyIDResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ApplyIDResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BootRequest struct {
	OsdId                int32    `protobuf:"varint,1,opt,name=osd_id,json=osdId,proto3" json:"osd_id,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Size_                int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Host                 string   `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootRequest) Reset()         { *m = BootRequest{} }
func (m *BootRequest) String() string { return proto.CompactTextString(m) }
func (*BootRequest) ProtoMessage()    {}
func (*BootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{9}
}
func (m *BootRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootRequest.Unmarshal(m, b)
}
func (m *BootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootRequest.Marshal(b, m, deterministic)
}
func (m *BootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootRequest.Merge(m, src)
}
func (m *BootRequest) XXX_Size() int {
	return xxx_messageInfo_BootRequest.Size(m)
}
func (m *BootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BootRequest proto.InternalMessageInfo

func (m *BootRequest) GetOsdId() int32 {
	if m != nil {
		return m.OsdId
	}
	return 0
}

func (m *BootRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BootRequest) GetSize_() int64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *BootRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *BootRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *BootRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type PGInfo struct {
	Pgid                 int32    `protobuf:"varint,1,opt,name=pgid,proto3" json:"pgid,omitempty"`
	Version              int64    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Osdid                []int32  `protobuf:"varint,3,rep,packed,name=osdid,proto3" json:"osdid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PGInfo) Reset()         { *m = PGInfo{} }
func (m *PGInfo) String() string { return proto.CompactTextString(m) }
func (*PGInfo) ProtoMessage()    {}
func (*PGInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{10}
}
func (m *PGInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PGInfo.Unmarshal(m, b)
}
func (m *PGInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PGInfo.Marshal(b, m, deterministic)
}
func (m *PGInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PGInfo.Merge(m, src)
}
func (m *PGInfo) XXX_Size() int {
	return xxx_messageInfo_PGInfo.Size(m)
}
func (m *PGInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PGInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PGInfo proto.InternalMessageInfo

func (m *PGInfo) GetPgid() int32 {
	if m != nil {
		return m.Pgid
	}
	return 0
}

func (m *PGInfo) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PGInfo) GetOsdid() []int32 {
	if m != nil {
		return m.Osdid
	}
	return nil
}

type PGInfos struct {
	Pi                   []*PGInfo `protobuf:"bytes,1,rep,name=pi,proto3" json:"pi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PGInfos) Reset()         { *m = PGInfos{} }
func (m *PGInfos) String() string { return proto.CompactTextString(m) }
func (*PGInfos) ProtoMessage()    {}
func (*PGInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{11}
}
func (m *PGInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PGInfos.Unmarshal(m, b)
}
func (m *PGInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PGInfos.Marshal(b, m, deterministic)
}
func (m *PGInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PGInfos.Merge(m, src)
}
func (m *PGInfos) XXX_Size() int {
	return xxx_messageInfo_PGInfos.Size(m)
}
func (m *PGInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_PGInfos.DiscardUnknown(m)
}

var xxx_messageInfo_PGInfos proto.InternalMessageInfo

func (m *PGInfos) GetPi() []*PGInfo {
	if m != nil {
		return m.Pi
	}
	return nil
}

type GetPgMapRequest struct {
	PoolVersions         map[int32]int64 `protobuf:"bytes,1,rep,name=pool_versions,json=poolVersions,proto3" json:"pool_versions,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetPgMapRequest) Reset()         { *m = GetPgMapRequest{} }
func (m *GetPgMapRequest) String() string { return proto.CompactTextString(m) }
func (*GetPgMapRequest) ProtoMessage()    {}
func (*GetPgMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{12}
}
func (m *GetPgMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPgMapRequest.Unmarshal(m, b)
}
func (m *GetPgMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPgMapRequest.Marshal(b, m, deterministic)
}
func (m *GetPgMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPgMapRequest.Merge(m, src)
}
func (m *GetPgMapRequest) XXX_Size() int {
	return xxx_messageInfo_GetPgMapRequest.Size(m)
}
func (m *GetPgMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPgMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPgMapRequest proto.InternalMessageInfo

func (m *GetPgMapRequest) GetPoolVersions() map[int32]int64 {
	if m != nil {
		return m.PoolVersions
	}
	return nil
}

// when osd restarts, following infomation is changed(host may not)
type OsdDynamicInfo struct {
	Osdid                int32    `protobuf:"varint,1,opt,name=osdid,proto3" json:"osdid,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Isin                 bool     `protobuf:"varint,4,opt,name=isin,proto3" json:"isin,omitempty"`
	Isup                 bool     `protobuf:"varint,5,opt,name=isup,proto3" json:"isup,omitempty"`
	Ispendingcreate      bool     `protobuf:"varint,6,opt,name=ispendingcreate,proto3" json:"ispendingcreate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OsdDynamicInfo) Reset()         { *m = OsdDynamicInfo{} }
func (m *OsdDynamicInfo) String() string { return proto.CompactTextString(m) }
func (*OsdDynamicInfo) ProtoMessage()    {}
func (*OsdDynamicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{13}
}
func (m *OsdDynamicInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OsdDynamicInfo.Unmarshal(m, b)
}
func (m *OsdDynamicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OsdDynamicInfo.Marshal(b, m, deterministic)
}
func (m *OsdDynamicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OsdDynamicInfo.Merge(m, src)
}
func (m *OsdDynamicInfo) XXX_Size() int {
	return xxx_messageInfo_OsdDynamicInfo.Size(m)
}
func (m *OsdDynamicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OsdDynamicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OsdDynamicInfo proto.InternalMessageInfo

func (m *OsdDynamicInfo) GetOsdid() int32 {
	if m != nil {
		return m.Osdid
	}
	return 0
}

func (m *OsdDynamicInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *OsdDynamicInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *OsdDynamicInfo) GetIsin() bool {
	if m != nil {
		return m.Isin
	}
	return false
}

func (m *OsdDynamicInfo) GetIsup() bool {
	if m != nil {
		return m.Isup
	}
	return false
}

func (m *OsdDynamicInfo) GetIspendingcreate() bool {
	if m != nil {
		return m.Ispendingcreate
	}
	return false
}

type GetPgMapResponse struct {
	Errorcode            map[int32]GetPgMapErrorCode `protobuf:"bytes,1,rep,name=errorcode,proto3" json:"errorcode,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=msg.GetPgMapErrorCode"`
	PoolidPgmapversion   map[int32]int64             `protobuf:"bytes,2,rep,name=poolid_pgmapversion,json=poolidPgmapversion,proto3" json:"poolid_pgmapversion,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Pgs                  map[int32]*PGInfos          `protobuf:"bytes,3,rep,name=pgs,proto3" json:"pgs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetPgMapResponse) Reset()         { *m = GetPgMapResponse{} }
func (m *GetPgMapResponse) String() string { return proto.CompactTextString(m) }
func (*GetPgMapResponse) ProtoMessage()    {}
func (*GetPgMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{14}
}
func (m *GetPgMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPgMapResponse.Unmarshal(m, b)
}
func (m *GetPgMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPgMapResponse.Marshal(b, m, deterministic)
}
func (m *GetPgMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPgMapResponse.Merge(m, src)
}
func (m *GetPgMapResponse) XXX_Size() int {
	return xxx_messageInfo_GetPgMapResponse.Size(m)
}
func (m *GetPgMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPgMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPgMapResponse proto.InternalMessageInfo

func (m *GetPgMapResponse) GetErrorcode() map[int32]GetPgMapErrorCode {
	if m != nil {
		return m.Errorcode
	}
	return nil
}

func (m *GetPgMapResponse) GetPoolidPgmapversion() map[int32]int64 {
	if m != nil {
		return m.PoolidPgmapversion
	}
	return nil
}

func (m *GetPgMapResponse) GetPgs() map[int32]*PGInfos {
	if m != nil {
		return m.Pgs
	}
	return nil
}

type GetOsdMapRequest struct {
	Osdid                int32    `protobuf:"varint,1,opt,name=osdid,proto3" json:"osdid,omitempty"`
	Currentversion       int64    `protobuf:"varint,2,opt,name=currentversion,proto3" json:"currentversion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOsdMapRequest) Reset()         { *m = GetOsdMapRequest{} }
func (m *GetOsdMapRequest) String() string { return proto.CompactTextString(m) }
func (*GetOsdMapRequest) ProtoMessage()    {}
func (*GetOsdMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{15}
}
func (m *GetOsdMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOsdMapRequest.Unmarshal(m, b)
}
func (m *GetOsdMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOsdMapRequest.Marshal(b, m, deterministic)
}
func (m *GetOsdMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOsdMapRequest.Merge(m, src)
}
func (m *GetOsdMapRequest) XXX_Size() int {
	return xxx_messageInfo_GetOsdMapRequest.Size(m)
}
func (m *GetOsdMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOsdMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOsdMapRequest proto.InternalMessageInfo

func (m *GetOsdMapRequest) GetOsdid() int32 {
	if m != nil {
		return m.Osdid
	}
	return 0
}

func (m *GetOsdMapRequest) GetCurrentversion() int64 {
	if m != nil {
		return m.Currentversion
	}
	return 0
}

type GetOsdMapResponse struct {
	Errorcode            OsdMapErrorCode   `protobuf:"varint,1,opt,name=errorcode,proto3,enum=msg.OsdMapErrorCode" json:"errorcode,omitempty"`
	Osdmapversion        int64             `protobuf:"varint,2,opt,name=osdmapversion,proto3" json:"osdmapversion,omitempty"`
	Osds                 []*OsdDynamicInfo `protobuf:"bytes,3,rep,name=osds,proto3" json:"osds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetOsdMapResponse) Reset()         { *m = GetOsdMapResponse{} }
func (m *GetOsdMapResponse) String() string { return proto.CompactTextString(m) }
func (*GetOsdMapResponse) ProtoMessage()    {}
func (*GetOsdMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{16}
}
func (m *GetOsdMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOsdMapResponse.Unmarshal(m, b)
}
func (m *GetOsdMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOsdMapResponse.Marshal(b, m, deterministic)
}
func (m *GetOsdMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOsdMapResponse.Merge(m, src)
}
func (m *GetOsdMapResponse) XXX_Size() int {
	return xxx_messageInfo_GetOsdMapResponse.Size(m)
}
func (m *GetOsdMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOsdMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOsdMapResponse proto.InternalMessageInfo

func (m *GetOsdMapResponse) GetErrorcode() OsdMapErrorCode {
	if m != nil {
		return m.Errorcode
	}
	return OsdMapErrorCode_ok
}

func (m *GetOsdMapResponse) GetOsdmapversion() int64 {
	if m != nil {
		return m.Osdmapversion
	}
	return 0
}

func (m *GetOsdMapResponse) GetOsds() []*OsdDynamicInfo {
	if m != nil {
		return m.Osds
	}
	return nil
}

type GetClusterMapRequest struct {
	GomRequest           *GetOsdMapRequest `protobuf:"bytes,1,opt,name=gom_request,json=gomRequest,proto3" json:"gom_request,omitempty"`
	GpmRequest           *GetPgMapRequest  `protobuf:"bytes,2,opt,name=gpm_request,json=gpmRequest,proto3" json:"gpm_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetClusterMapRequest) Reset()         { *m = GetClusterMapRequest{} }
func (m *GetClusterMapRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterMapRequest) ProtoMessage()    {}
func (*GetClusterMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{17}
}
func (m *GetClusterMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterMapRequest.Unmarshal(m, b)
}
func (m *GetClusterMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterMapRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterMapRequest.Merge(m, src)
}
func (m *GetClusterMapRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterMapRequest.Size(m)
}
func (m *GetClusterMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterMapRequest proto.InternalMessageInfo

func (m *GetClusterMapRequest) GetGomRequest() *GetOsdMapRequest {
	if m != nil {
		return m.GomRequest
	}
	return nil
}

func (m *GetClusterMapRequest) GetGpmRequest() *GetPgMapRequest {
	if m != nil {
		return m.GpmRequest
	}
	return nil
}

type GetClusterMapResponse struct {
	GomResponse          *GetOsdMapResponse `protobuf:"bytes,1,opt,name=gom_response,json=gomResponse,proto3" json:"gom_response,omitempty"`
	GpmResponse          *GetPgMapResponse  `protobuf:"bytes,2,opt,name=gpm_response,json=gpmResponse,proto3" json:"gpm_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetClusterMapResponse) Reset()         { *m = GetClusterMapResponse{} }
func (m *GetClusterMapResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterMapResponse) ProtoMessage()    {}
func (*GetClusterMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{18}
}
func (m *GetClusterMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterMapResponse.Unmarshal(m, b)
}
func (m *GetClusterMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterMapResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterMapResponse.Merge(m, src)
}
func (m *GetClusterMapResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterMapResponse.Size(m)
}
func (m *GetClusterMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterMapResponse proto.InternalMessageInfo

func (m *GetClusterMapResponse) GetGomResponse() *GetOsdMapResponse {
	if m != nil {
		return m.GomResponse
	}
	return nil
}

func (m *GetClusterMapResponse) GetGpmResponse() *GetPgMapResponse {
	if m != nil {
		return m.GpmResponse
	}
	return nil
}

type BootResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootResponse) Reset()         { *m = BootResponse{} }
func (m *BootResponse) String() string { return proto.CompactTextString(m) }
func (*BootResponse) ProtoMessage()    {}
func (*BootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{19}
}
func (m *BootResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootResponse.Unmarshal(m, b)
}
func (m *BootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootResponse.Marshal(b, m, deterministic)
}
func (m *BootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootResponse.Merge(m, src)
}
func (m *BootResponse) XXX_Size() int {
	return xxx_messageInfo_BootResponse.Size(m)
}
func (m *BootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BootResponse proto.InternalMessageInfo

func (m *BootResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type OsdStopRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OsdStopRequest) Reset()         { *m = OsdStopRequest{} }
func (m *OsdStopRequest) String() string { return proto.CompactTextString(m) }
func (*OsdStopRequest) ProtoMessage()    {}
func (*OsdStopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{20}
}
func (m *OsdStopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OsdStopRequest.Unmarshal(m, b)
}
func (m *OsdStopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OsdStopRequest.Marshal(b, m, deterministic)
}
func (m *OsdStopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OsdStopRequest.Merge(m, src)
}
func (m *OsdStopRequest) XXX_Size() int {
	return xxx_messageInfo_OsdStopRequest.Size(m)
}
func (m *OsdStopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OsdStopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OsdStopRequest proto.InternalMessageInfo

func (m *OsdStopRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type OsdStopResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OsdStopResponse) Reset()         { *m = OsdStopResponse{} }
func (m *OsdStopResponse) String() string { return proto.CompactTextString(m) }
func (*OsdStopResponse) ProtoMessage()    {}
func (*OsdStopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{21}
}
func (m *OsdStopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OsdStopResponse.Unmarshal(m, b)
}
func (m *OsdStopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OsdStopResponse.Marshal(b, m, deterministic)
}
func (m *OsdStopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OsdStopResponse.Merge(m, src)
}
func (m *OsdStopResponse) XXX_Size() int {
	return xxx_messageInfo_OsdStopResponse.Size(m)
}
func (m *OsdStopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OsdStopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OsdStopResponse proto.InternalMessageInfo

func (m *OsdStopResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type HeartbeatRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{22}
}
func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type HeartbeatResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{23}
}
func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func (m *HeartbeatResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ImageInfo struct {
	Poolname             string   `protobuf:"bytes,1,opt,name=poolname,proto3" json:"poolname,omitempty"`
	Imagename            string   `protobuf:"bytes,2,opt,name=imagename,proto3" json:"imagename,omitempty"`
	Size_                int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ObjectSize           int64    `protobuf:"varint,4,opt,name=object_size,json=objectSize,proto3" json:"object_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageInfo) Reset()         { *m = ImageInfo{} }
func (m *ImageInfo) String() string { return proto.CompactTextString(m) }
func (*ImageInfo) ProtoMessage()    {}
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{24}
}
func (m *ImageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageInfo.Unmarshal(m, b)
}
func (m *ImageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageInfo.Marshal(b, m, deterministic)
}
func (m *ImageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageInfo.Merge(m, src)
}
func (m *ImageInfo) XXX_Size() int {
	return xxx_messageInfo_ImageInfo.Size(m)
}
func (m *ImageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ImageInfo proto.InternalMessageInfo

func (m *ImageInfo) GetPoolname() string {
	if m != nil {
		return m.Poolname
	}
	return ""
}

func (m *ImageInfo) GetImagename() string {
	if m != nil {
		return m.Imagename
	}
	return ""
}

func (m *ImageInfo) GetSize_() int64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *ImageInfo) GetObjectSize() int64 {
	if m != nil {
		return m.ObjectSize
	}
	return 0
}

type CreateImageRequest struct {
	Poolname             string   `protobuf:"bytes,1,opt,name=poolname,proto3" json:"poolname,omitempty"`
	Imagename            string   `protobuf:"bytes,2,opt,name=imagename,proto3" json:"imagename,omitempty"`
	Size_                int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ObjectSize           int64    `protobuf:"varint,4,opt,name=object_size,json=objectSize,proto3" json:"object_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateImageRequest) Reset()         { *m = CreateImageRequest{} }
func (m *CreateImageRequest) String() string { return proto.CompactTextString(m) }
func (*CreateImageRequest) ProtoMessage()    {}
func (*CreateImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{25}
}
func (m *CreateImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateImageRequest.Unmarshal(m, b)
}
func (m *CreateImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateImageRequest.Marshal(b, m, deterministic)
}
func (m *CreateImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateImageRequest.Merge(m, src)
}
func (m *CreateImageRequest) XXX_Size() int {
	return xxx_messageInfo_CreateImageRequest.Size(m)
}
func (m *CreateImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateImageRequest proto.InternalMessageInfo

func (m *CreateImageRequest) GetPoolname() string {
	if m != nil {
		return m.Poolname
	}
	return ""
}

func (m *CreateImageRequest) GetImagename() string {
	if m != nil {
		return m.Imagename
	}
	return ""
}

func (m *CreateImageRequest) GetSize_() int64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *CreateImageRequest) GetObjectSize() int64 {
	if m != nil {
		return m.ObjectSize
	}
	return 0
}

type CreateImageResponse struct {
	Errorcode            CreateImageErrorCode `protobuf:"varint,1,opt,name=errorcode,proto3,enum=msg.CreateImageErrorCode" json:"errorcode,omitempty"`
	ImageInfo            *ImageInfo           `protobuf:"bytes,2,opt,name=ImageInfo,proto3" json:"ImageInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateImageResponse) Reset()         { *m = CreateImageResponse{} }
func (m *CreateImageResponse) String() string { return proto.CompactTextString(m) }
func (*CreateImageResponse) ProtoMessage()    {}
func (*CreateImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{26}
}
func (m *CreateImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateImageResponse.Unmarshal(m, b)
}
func (m *CreateImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateImageResponse.Marshal(b, m, deterministic)
}
func (m *CreateImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateImageResponse.Merge(m, src)
}
func (m *CreateImageResponse) XXX_Size() int {
	return xxx_messageInfo_CreateImageResponse.Size(m)
}
func (m *CreateImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateImageResponse proto.InternalMessageInfo

func (m *CreateImageResponse) GetErrorcode() CreateImageErrorCode {
	if m != nil {
		return m.Errorcode
	}
	return CreateImageErrorCode_createImageOk
}

func (m *CreateImageResponse) GetImageInfo() *ImageInfo {
	if m != nil {
		return m.ImageInfo
	}
	return nil
}

type RemoveImageRequest struct {
	Poolname             string   `protobuf:"bytes,1,opt,name=poolname,proto3" json:"poolname,omitempty"`
	Imagename            string   `protobuf:"bytes,2,opt,name=imagename,proto3" json:"imagename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveImageRequest) Reset()         { *m = RemoveImageRequest{} }
func (m *RemoveImageRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveImageRequest) ProtoMessage()    {}
func (*RemoveImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{27}
}
func (m *RemoveImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveImageRequest.Unmarshal(m, b)
}
func (m *RemoveImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveImageRequest.Marshal(b, m, deterministic)
}
func (m *RemoveImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveImageRequest.Merge(m, src)
}
func (m *RemoveImageRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveImageRequest.Size(m)
}
func (m *RemoveImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveImageRequest proto.InternalMessageInfo

func (m *RemoveImageRequest) GetPoolname() string {
	if m != nil {
		return m.Poolname
	}
	return ""
}

func (m *RemoveImageRequest) GetImagename() string {
	if m != nil {
		return m.Imagename
	}
	return ""
}

type RemoveImageResponse struct {
	Errorcode            RemoveImageErrorCode `protobuf:"varint,1,opt,name=errorcode,proto3,enum=msg.RemoveImageErrorCode" json:"errorcode,omitempty"`
	ImageInfo            *ImageInfo           `protobuf:"bytes,2,opt,name=ImageInfo,proto3" json:"ImageInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RemoveImageResponse) Reset()         { *m = RemoveImageResponse{} }
func (m *RemoveImageResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveImageResponse) ProtoMessage()    {}
func (*RemoveImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{28}
}
func (m *RemoveImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveImageResponse.Unmarshal(m, b)
}
func (m *RemoveImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveImageResponse.Marshal(b, m, deterministic)
}
func (m *RemoveImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveImageResponse.Merge(m, src)
}
func (m *RemoveImageResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveImageResponse.Size(m)
}
func (m *RemoveImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveImageResponse proto.InternalMessageInfo

func (m *RemoveImageResponse) GetErrorcode() RemoveImageErrorCode {
	if m != nil {
		return m.Errorcode
	}
	return RemoveImageErrorCode_removeImageOk
}

func (m *RemoveImageResponse) GetImageInfo() *ImageInfo {
	if m != nil {
		return m.ImageInfo
	}
	return nil
}

type ResizeImageRequest struct {
	Poolname             string   `protobuf:"bytes,1,opt,name=poolname,proto3" json:"poolname,omitempty"`
	Imagename            string   `protobuf:"bytes,2,opt,name=imagename,proto3" json:"imagename,omitempty"`
	Size_                int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResizeImageRequest) Reset()         { *m = ResizeImageRequest{} }
func (m *ResizeImageRequest) String() string { return proto.CompactTextString(m) }
func (*ResizeImageRequest) ProtoMessage()    {}
func (*ResizeImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{29}
}
func (m *ResizeImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResizeImageRequest.Unmarshal(m, b)
}
func (m *ResizeImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResizeImageRequest.Marshal(b, m, deterministic)
}
func (m *ResizeImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResizeImageRequest.Merge(m, src)
}
func (m *ResizeImageRequest) XXX_Size() int {
	return xxx_messageInfo_ResizeImageRequest.Size(m)
}
func (m *ResizeImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResizeImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResizeImageRequest proto.InternalMessageInfo

func (m *ResizeImageRequest) GetPoolname() string {
	if m != nil {
		return m.Poolname
	}
	return ""
}

func (m *ResizeImageRequest) GetImagename() string {
	if m != nil {
		return m.Imagename
	}
	return ""
}

func (m *ResizeImageRequest) GetSize_() int64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

type ResizeImageResponse struct {
	Errorcode            ResizeImageErrorCode `protobuf:"varint,1,opt,name=errorcode,proto3,enum=msg.ResizeImageErrorCode" json:"errorcode,omitempty"`
	ImageInfo            *ImageInfo           `protobuf:"bytes,2,opt,name=ImageInfo,proto3" json:"ImageInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResizeImageResponse) Reset()         { *m = ResizeImageResponse{} }
func (m *ResizeImageResponse) String() string { return proto.CompactTextString(m) }
func (*ResizeImageResponse) ProtoMessage()    {}
func (*ResizeImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{30}
}
func (m *ResizeImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResizeImageResponse.Unmarshal(m, b)
}
func (m *ResizeImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResizeImageResponse.Marshal(b, m, deterministic)
}
func (m *ResizeImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResizeImageResponse.Merge(m, src)
}
func (m *ResizeImageResponse) XXX_Size() int {
	return xxx_messageInfo_ResizeImageResponse.Size(m)
}
func (m *ResizeImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResizeImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResizeImageResponse proto.InternalMessageInfo

func (m *ResizeImageResponse) GetErrorcode() ResizeImageErrorCode {
	if m != nil {
		return m.Errorcode
	}
	return ResizeImageErrorCode_resizeImageOk
}

func (m *ResizeImageResponse) GetImageInfo() *ImageInfo {
	if m != nil {
		return m.ImageInfo
	}
	return nil
}

type GetImageInfoRequest struct {
	Poolname             string   `protobuf:"bytes,1,opt,name=poolname,proto3" json:"poolname,omitempty"`
	Imagename            string   `protobuf:"bytes,2,opt,name=imagename,proto3" json:"imagename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetImageInfoRequest) Reset()         { *m = GetImageInfoRequest{} }
func (m *GetImageInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetImageInfoRequest) ProtoMessage()    {}
func (*GetImageInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{31}
}
func (m *GetImageInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetImageInfoRequest.Unmarshal(m, b)
}
func (m *GetImageInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetImageInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetImageInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetImageInfoRequest.Merge(m, src)
}
func (m *GetImageInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetImageInfoRequest.Size(m)
}
func (m *GetImageInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetImageInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetImageInfoRequest proto.InternalMessageInfo

func (m *GetImageInfoRequest) GetPoolname() string {
	if m != nil {
		return m.Poolname
	}
	return ""
}

func (m *GetImageInfoRequest) GetImagename() string {
	if m != nil {
		return m.Imagename
	}
	return ""
}

type GetImageInfoResponse struct {
	Errorcode            GetImageErrorCode `protobuf:"varint,1,opt,name=errorcode,proto3,enum=msg.GetImageErrorCode" json:"errorcode,omitempty"`
	ImageInfo            *ImageInfo        `protobuf:"bytes,2,opt,name=ImageInfo,proto3" json:"ImageInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetImageInfoResponse) Reset()         { *m = GetImageInfoResponse{} }
func (m *GetImageInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetImageInfoResponse) ProtoMessage()    {}
func (*GetImageInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{32}
}
func (m *GetImageInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetImageInfoResponse.Unmarshal(m, b)
}
func (m *GetImageInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetImageInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetImageInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetImageInfoResponse.Merge(m, src)
}
func (m *GetImageInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetImageInfoResponse.Size(m)
}
func (m *GetImageInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetImageInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetImageInfoResponse proto.InternalMessageInfo

func (m *GetImageInfoResponse) GetErrorcode() GetImageErrorCode {
	if m != nil {
		return m.Errorcode
	}
	return GetImageErrorCode_getImageOk
}

func (m *GetImageInfoResponse) GetImageInfo() *ImageInfo {
	if m != nil {
		return m.ImageInfo
	}
	return nil
}

type Request struct {
	// Types that are valid to be assigned to Union:
	//	*Request_BootRequest
	//	*Request_OsdStopRequest
	//	*Request_HeartbeatRequest
	//	*Request_GetOsdmapRequest
	//	*Request_ListPoolsRequest
	//	*Request_ApplyIdRequest
	//	*Request_CreatePoolRequest
	//	*Request_GetPgmapRequest
	//	*Request_DeletePoolRequest
	//	*Request_GetClusterMapRequest
	//	*Request_CreateImageRequest
	//	*Request_RemoveImageRequest
	//	*Request_ResizeImageRequest
	//	*Request_Get_ImageInfo_Request
	Union                isRequest_Union `protobuf_oneof:"union"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{33}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type isRequest_Union interface {
	isRequest_Union()
}

type Request_BootRequest struct {
	BootRequest *BootRequest `protobuf:"bytes,1,opt,name=boot_request,json=bootRequest,proto3,oneof" json:"boot_request,omitempty"`
}
type Request_OsdStopRequest struct {
	OsdStopRequest *OsdStopRequest `protobuf:"bytes,2,opt,name=osd_stop_request,json=osdStopRequest,proto3,oneof" json:"osd_stop_request,omitempty"`
}
type Request_HeartbeatRequest struct {
	HeartbeatRequest *HeartbeatRequest `protobuf:"bytes,3,opt,name=heartbeat_request,json=heartbeatRequest,proto3,oneof" json:"heartbeat_request,omitempty"`
}
type Request_GetOsdmapRequest struct {
	GetOsdmapRequest *GetOsdMapRequest `protobuf:"bytes,4,opt,name=get_osdmap_request,json=getOsdmapRequest,proto3,oneof" json:"get_osdmap_request,omitempty"`
}
type Request_ListPoolsRequest struct {
	ListPoolsRequest *ListPoolsRequest `protobuf:"bytes,5,opt,name=list_pools_request,json=listPoolsRequest,proto3,oneof" json:"list_pools_request,omitempty"`
}
type Request_ApplyIdRequest struct {
	ApplyIdRequest *ApplyIDRequest `protobuf:"bytes,6,opt,name=apply_id_request,json=applyIdRequest,proto3,oneof" json:"apply_id_request,omitempty"`
}
type Request_CreatePoolRequest struct {
	CreatePoolRequest *CreatePoolRequest `protobuf:"bytes,7,opt,name=create_pool_request,json=createPoolRequest,proto3,oneof" json:"create_pool_request,omitempty"`
}
type Request_GetPgmapRequest struct {
	GetPgmapRequest *GetPgMapRequest `protobuf:"bytes,8,opt,name=get_pgmap_request,json=getPgmapRequest,proto3,oneof" json:"get_pgmap_request,omitempty"`
}
type Request_DeletePoolRequest struct {
	DeletePoolRequest *DeletePoolRequest `protobuf:"bytes,9,opt,name=delete_pool_request,json=deletePoolRequest,proto3,oneof" json:"delete_pool_request,omitempty"`
}
type Request_GetClusterMapRequest struct {
	GetClusterMapRequest *GetClusterMapRequest `protobuf:"bytes,10,opt,name=get_cluster_map_request,json=getClusterMapRequest,proto3,oneof" json:"get_cluster_map_request,omitempty"`
}
type Request_CreateImageRequest struct {
	CreateImageRequest *CreateImageRequest `protobuf:"bytes,11,opt,name=create_image_request,json=createImageRequest,proto3,oneof" json:"create_image_request,omitempty"`
}
type Request_RemoveImageRequest struct {
	RemoveImageRequest *RemoveImageRequest `protobuf:"bytes,12,opt,name=remove_image_request,json=removeImageRequest,proto3,oneof" json:"remove_image_request,omitempty"`
}
type Request_ResizeImageRequest struct {
	ResizeImageRequest *ResizeImageRequest `protobuf:"bytes,13,opt,name=resize_image_request,json=resizeImageRequest,proto3,oneof" json:"resize_image_request,omitempty"`
}
type Request_Get_ImageInfo_Request struct {
	Get_ImageInfo_Request *GetImageInfoRequest `protobuf:"bytes,14,opt,name=get_ImageInfo_Request,json=getImageInfoRequest,proto3,oneof" json:"get_ImageInfo_Request,omitempty"`
}

func (*Request_BootRequest) isRequest_Union()           {}
func (*Request_OsdStopRequest) isRequest_Union()        {}
func (*Request_HeartbeatRequest) isRequest_Union()      {}
func (*Request_GetOsdmapRequest) isRequest_Union()      {}
func (*Request_ListPoolsRequest) isRequest_Union()      {}
func (*Request_ApplyIdRequest) isRequest_Union()        {}
func (*Request_CreatePoolRequest) isRequest_Union()     {}
func (*Request_GetPgmapRequest) isRequest_Union()       {}
func (*Request_DeletePoolRequest) isRequest_Union()     {}
func (*Request_GetClusterMapRequest) isRequest_Union()  {}
func (*Request_CreateImageRequest) isRequest_Union()    {}
func (*Request_RemoveImageRequest) isRequest_Union()    {}
func (*Request_ResizeImageRequest) isRequest_Union()    {}
func (*Request_Get_ImageInfo_Request) isRequest_Union() {}

func (m *Request) GetUnion() isRequest_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (m *Request) GetBootRequest() *BootRequest {
	if x, ok := m.GetUnion().(*Request_BootRequest); ok {
		return x.BootRequest
	}
	return nil
}

func (m *Request) GetOsdStopRequest() *OsdStopRequest {
	if x, ok := m.GetUnion().(*Request_OsdStopRequest); ok {
		return x.OsdStopRequest
	}
	return nil
}

func (m *Request) GetHeartbeatRequest() *HeartbeatRequest {
	if x, ok := m.GetUnion().(*Request_HeartbeatRequest); ok {
		return x.HeartbeatRequest
	}
	return nil
}

func (m *Request) GetGetOsdmapRequest() *GetOsdMapRequest {
	if x, ok := m.GetUnion().(*Request_GetOsdmapRequest); ok {
		return x.GetOsdmapRequest
	}
	return nil
}

func (m *Request) GetListPoolsRequest() *ListPoolsRequest {
	if x, ok := m.GetUnion().(*Request_ListPoolsRequest); ok {
		return x.ListPoolsRequest
	}
	return nil
}

func (m *Request) GetApplyIdRequest() *ApplyIDRequest {
	if x, ok := m.GetUnion().(*Request_ApplyIdRequest); ok {
		return x.ApplyIdRequest
	}
	return nil
}

func (m *Request) GetCreatePoolRequest() *CreatePoolRequest {
	if x, ok := m.GetUnion().(*Request_CreatePoolRequest); ok {
		return x.CreatePoolRequest
	}
	return nil
}

func (m *Request) GetGetPgmapRequest() *GetPgMapRequest {
	if x, ok := m.GetUnion().(*Request_GetPgmapRequest); ok {
		return x.GetPgmapRequest
	}
	return nil
}

func (m *Request) GetDeletePoolRequest() *DeletePoolRequest {
	if x, ok := m.GetUnion().(*Request_DeletePoolRequest); ok {
		return x.DeletePoolRequest
	}
	return nil
}

func (m *Request) GetGetClusterMapRequest() *GetClusterMapRequest {
	if x, ok := m.GetUnion().(*Request_GetClusterMapRequest); ok {
		return x.GetClusterMapRequest
	}
	return nil
}

func (m *Request) GetCreateImageRequest() *CreateImageRequest {
	if x, ok := m.GetUnion().(*Request_CreateImageRequest); ok {
		return x.CreateImageRequest
	}
	return nil
}

func (m *Request) GetRemoveImageRequest() *RemoveImageRequest {
	if x, ok := m.GetUnion().(*Request_RemoveImageRequest); ok {
		return x.RemoveImageRequest
	}
	return nil
}

func (m *Request) GetResizeImageRequest() *ResizeImageRequest {
	if x, ok := m.GetUnion().(*Request_ResizeImageRequest); ok {
		return x.ResizeImageRequest
	}
	return nil
}

func (m *Request) GetGet_ImageInfo_Request() *GetImageInfoRequest {
	if x, ok := m.GetUnion().(*Request_Get_ImageInfo_Request); ok {
		return x.Get_ImageInfo_Request
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_BootRequest)(nil),
		(*Request_OsdStopRequest)(nil),
		(*Request_HeartbeatRequest)(nil),
		(*Request_GetOsdmapRequest)(nil),
		(*Request_ListPoolsRequest)(nil),
		(*Request_ApplyIdRequest)(nil),
		(*Request_CreatePoolRequest)(nil),
		(*Request_GetPgmapRequest)(nil),
		(*Request_DeletePoolRequest)(nil),
		(*Request_GetClusterMapRequest)(nil),
		(*Request_CreateImageRequest)(nil),
		(*Request_RemoveImageRequest)(nil),
		(*Request_ResizeImageRequest)(nil),
		(*Request_Get_ImageInfo_Request)(nil),
	}
}

type Response struct {
	// Types that are valid to be assigned to Union:
	//	*Response_BootResponse
	//	*Response_OsdStopResponse
	//	*Response_HeartbeatResponse
	//	*Response_GetOsdmapResponse
	//	*Response_ListPoolsResponse
	//	*Response_ApplyIdResponse
	//	*Response_CreatePoolResponse
	//	*Response_GetPgmapResponse
	//	*Response_DeletePoolResponse
	//	*Response_GetClusterMapResponse
	//	*Response_CreateImageResponse
	//	*Response_RemoveImageResponse
	//	*Response_ResizeImageResponse
	//	*Response_GetImageInfoResponse
	Union                isResponse_Union `protobuf_oneof:"union"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{34}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type isResponse_Union interface {
	isResponse_Union()
}

type Response_BootResponse struct {
	BootResponse *BootResponse `protobuf:"bytes,1,opt,name=boot_response,json=bootResponse,proto3,oneof" json:"boot_response,omitempty"`
}
type Response_OsdStopResponse struct {
	OsdStopResponse *OsdStopResponse `protobuf:"bytes,2,opt,name=osd_stop_response,json=osdStopResponse,proto3,oneof" json:"osd_stop_response,omitempty"`
}
type Response_HeartbeatResponse struct {
	HeartbeatResponse *HeartbeatResponse `protobuf:"bytes,3,opt,name=heartbeat_response,json=heartbeatResponse,proto3,oneof" json:"heartbeat_response,omitempty"`
}
type Response_GetOsdmapResponse struct {
	GetOsdmapResponse *GetOsdMapResponse `protobuf:"bytes,4,opt,name=get_osdmap_response,json=getOsdmapResponse,proto3,oneof" json:"get_osdmap_response,omitempty"`
}
type Response_ListPoolsResponse struct {
	ListPoolsResponse *ListPoolsResponse `protobuf:"bytes,5,opt,name=list_pools_response,json=listPoolsResponse,proto3,oneof" json:"list_pools_response,omitempty"`
}
type Response_ApplyIdResponse struct {
	ApplyIdResponse *ApplyIDResponse `protobuf:"bytes,6,opt,name=apply_id_response,json=applyIdResponse,proto3,oneof" json:"apply_id_response,omitempty"`
}
type Response_CreatePoolResponse struct {
	CreatePoolResponse *CreatePoolResponse `protobuf:"bytes,7,opt,name=create_pool_response,json=createPoolResponse,proto3,oneof" json:"create_pool_response,omitempty"`
}
type Response_GetPgmapResponse struct {
	GetPgmapResponse *GetPgMapResponse `protobuf:"bytes,8,opt,name=get_pgmap_response,json=getPgmapResponse,proto3,oneof" json:"get_pgmap_response,omitempty"`
}
type Response_DeletePoolResponse struct {
	DeletePoolResponse *DeletePoolResponse `protobuf:"bytes,9,opt,name=delete_pool_response,json=deletePoolResponse,proto3,oneof" json:"delete_pool_response,omitempty"`
}
type Response_GetClusterMapResponse struct {
	GetClusterMapResponse *GetClusterMapResponse `protobuf:"bytes,10,opt,name=get_cluster_map_response,json=getClusterMapResponse,proto3,oneof" json:"get_cluster_map_response,omitempty"`
}
type Response_CreateImageResponse struct {
	CreateImageResponse *CreateImageResponse `protobuf:"bytes,11,opt,name=create_image_response,json=createImageResponse,proto3,oneof" json:"create_image_response,omitempty"`
}
type Response_RemoveImageResponse struct {
	RemoveImageResponse *RemoveImageResponse `protobuf:"bytes,12,opt,name=remove_image_response,json=removeImageResponse,proto3,oneof" json:"remove_image_response,omitempty"`
}
type Response_ResizeImageResponse struct {
	ResizeImageResponse *ResizeImageResponse `protobuf:"bytes,13,opt,name=resize_image_response,json=resizeImageResponse,proto3,oneof" json:"resize_image_response,omitempty"`
}
type Response_GetImageInfoResponse struct {
	GetImageInfoResponse *GetImageInfoResponse `protobuf:"bytes,14,opt,name=get_imageInfo_response,json=getImageInfoResponse,proto3,oneof" json:"get_imageInfo_response,omitempty"`
}

func (*Response_BootResponse) isResponse_Union()          {}
func (*Response_OsdStopResponse) isResponse_Union()       {}
func (*Response_HeartbeatResponse) isResponse_Union()     {}
func (*Response_GetOsdmapResponse) isResponse_Union()     {}
func (*Response_ListPoolsResponse) isResponse_Union()     {}
func (*Response_ApplyIdResponse) isResponse_Union()       {}
func (*Response_CreatePoolResponse) isResponse_Union()    {}
func (*Response_GetPgmapResponse) isResponse_Union()      {}
func (*Response_DeletePoolResponse) isResponse_Union()    {}
func (*Response_GetClusterMapResponse) isResponse_Union() {}
func (*Response_CreateImageResponse) isResponse_Union()   {}
func (*Response_RemoveImageResponse) isResponse_Union()   {}
func (*Response_ResizeImageResponse) isResponse_Union()   {}
func (*Response_GetImageInfoResponse) isResponse_Union()  {}

func (m *Response) GetUnion() isResponse_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (m *Response) GetBootResponse() *BootResponse {
	if x, ok := m.GetUnion().(*Response_BootResponse); ok {
		return x.BootResponse
	}
	return nil
}

func (m *Response) GetOsdStopResponse() *OsdStopResponse {
	if x, ok := m.GetUnion().(*Response_OsdStopResponse); ok {
		return x.OsdStopResponse
	}
	return nil
}

func (m *Response) GetHeartbeatResponse() *HeartbeatResponse {
	if x, ok := m.GetUnion().(*Response_HeartbeatResponse); ok {
		return x.HeartbeatResponse
	}
	return nil
}

func (m *Response) GetGetOsdmapResponse() *GetOsdMapResponse {
	if x, ok := m.GetUnion().(*Response_GetOsdmapResponse); ok {
		return x.GetOsdmapResponse
	}
	return nil
}

func (m *Response) GetListPoolsResponse() *ListPoolsResponse {
	if x, ok := m.GetUnion().(*Response_ListPoolsResponse); ok {
		return x.ListPoolsResponse
	}
	return nil
}

func (m *Response) GetApplyIdResponse() *ApplyIDResponse {
	if x, ok := m.GetUnion().(*Response_ApplyIdResponse); ok {
		return x.ApplyIdResponse
	}
	return nil
}

func (m *Response) GetCreatePoolResponse() *CreatePoolResponse {
	if x, ok := m.GetUnion().(*Response_CreatePoolResponse); ok {
		return x.CreatePoolResponse
	}
	return nil
}

func (m *Response) GetGetPgmapResponse() *GetPgMapResponse {
	if x, ok := m.GetUnion().(*Response_GetPgmapResponse); ok {
		return x.GetPgmapResponse
	}
	return nil
}

func (m *Response) GetDeletePoolResponse() *DeletePoolResponse {
	if x, ok := m.GetUnion().(*Response_DeletePoolResponse); ok {
		return x.DeletePoolResponse
	}
	return nil
}

func (m *Response) GetGetClusterMapResponse() *GetClusterMapResponse {
	if x, ok := m.GetUnion().(*Response_GetClusterMapResponse); ok {
		return x.GetClusterMapResponse
	}
	return nil
}

func (m *Response) GetCreateImageResponse() *CreateImageResponse {
	if x, ok := m.GetUnion().(*Response_CreateImageResponse); ok {
		return x.CreateImageResponse
	}
	return nil
}

func (m *Response) GetRemoveImageResponse() *RemoveImageResponse {
	if x, ok := m.GetUnion().(*Response_RemoveImageResponse); ok {
		return x.RemoveImageResponse
	}
	return nil
}

func (m *Response) GetResizeImageResponse() *ResizeImageResponse {
	if x, ok := m.GetUnion().(*Response_ResizeImageResponse); ok {
		return x.ResizeImageResponse
	}
	return nil
}

func (m *Response) GetGetImageInfoResponse() *GetImageInfoResponse {
	if x, ok := m.GetUnion().(*Response_GetImageInfoResponse); ok {
		return x.GetImageInfoResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_BootResponse)(nil),
		(*Response_OsdStopResponse)(nil),
		(*Response_HeartbeatResponse)(nil),
		(*Response_GetOsdmapResponse)(nil),
		(*Response_ListPoolsResponse)(nil),
		(*Response_ApplyIdResponse)(nil),
		(*Response_CreatePoolResponse)(nil),
		(*Response_GetPgmapResponse)(nil),
		(*Response_DeletePoolResponse)(nil),
		(*Response_GetClusterMapResponse)(nil),
		(*Response_CreateImageResponse)(nil),
		(*Response_RemoveImageResponse)(nil),
		(*Response_ResizeImageResponse)(nil),
		(*Response_GetImageInfoResponse)(nil),
	}
}

func init() {
	proto.RegisterEnum("msg.GetPgMapErrorCode", GetPgMapErrorCode_name, GetPgMapErrorCode_value)
	proto.RegisterEnum("msg.OsdMapErrorCode", OsdMapErrorCode_name, OsdMapErrorCode_value)
	proto.RegisterEnum("msg.CreateImageErrorCode", CreateImageErrorCode_name, CreateImageErrorCode_value)
	proto.RegisterEnum("msg.RemoveImageErrorCode", RemoveImageErrorCode_name, RemoveImageErrorCode_value)
	proto.RegisterEnum("msg.ResizeImageErrorCode", ResizeImageErrorCode_name, ResizeImageErrorCode_value)
	proto.RegisterEnum("msg.GetImageErrorCode", GetImageErrorCode_name, GetImageErrorCode_value)
	proto.RegisterType((*CreatePoolRequest)(nil), "msg.CreatePoolRequest")
	proto.RegisterType((*CreatePoolResponse)(nil), "msg.CreatePoolResponse")
	proto.RegisterType((*ListPoolsRequest)(nil), "msg.ListPoolsRequest")
	proto.RegisterType((*Poolinfo)(nil), "msg.poolinfo")
	proto.RegisterType((*ListPoolsResponse)(nil), "msg.ListPoolsResponse")
	proto.RegisterType((*DeletePoolRequest)(nil), "msg.DeletePoolRequest")
	proto.RegisterType((*DeletePoolResponse)(nil), "msg.DeletePoolResponse")
	proto.RegisterType((*ApplyIDRequest)(nil), "msg.ApplyIDRequest")
	proto.RegisterType((*ApplyIDResponse)(nil), "msg.ApplyIDResponse")
	proto.RegisterType((*BootRequest)(nil), "msg.BootRequest")
	proto.RegisterType((*PGInfo)(nil), "msg.PGInfo")
	proto.RegisterType((*PGInfos)(nil), "msg.PGInfos")
	proto.RegisterType((*GetPgMapRequest)(nil), "msg.GetPgMapRequest")
	proto.RegisterMapType((map[int32]int64)(nil), "msg.GetPgMapRequest.PoolVersionsEntry")
	proto.RegisterType((*OsdDynamicInfo)(nil), "msg.OsdDynamicInfo")
	proto.RegisterType((*GetPgMapResponse)(nil), "msg.GetPgMapResponse")
	proto.RegisterMapType((map[int32]GetPgMapErrorCode)(nil), "msg.GetPgMapResponse.ErrorcodeEntry")
	proto.RegisterMapType((map[int32]*PGInfos)(nil), "msg.GetPgMapResponse.PgsEntry")
	proto.RegisterMapType((map[int32]int64)(nil), "msg.GetPgMapResponse.PoolidPgmapversionEntry")
	proto.RegisterType((*GetOsdMapRequest)(nil), "msg.GetOsdMapRequest")
	proto.RegisterType((*GetOsdMapResponse)(nil), "msg.GetOsdMapResponse")
	proto.RegisterType((*GetClusterMapRequest)(nil), "msg.GetClusterMapRequest")
	proto.RegisterType((*GetClusterMapResponse)(nil), "msg.GetClusterMapResponse")
	proto.RegisterType((*BootResponse)(nil), "msg.BootResponse")
	proto.RegisterType((*OsdStopRequest)(nil), "msg.OsdStopRequest")
	proto.RegisterType((*OsdStopResponse)(nil), "msg.OsdStopResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "msg.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "msg.HeartbeatResponse")
	proto.RegisterType((*ImageInfo)(nil), "msg.ImageInfo")
	proto.RegisterType((*CreateImageRequest)(nil), "msg.CreateImageRequest")
	proto.RegisterType((*CreateImageResponse)(nil), "msg.CreateImageResponse")
	proto.RegisterType((*RemoveImageRequest)(nil), "msg.RemoveImageRequest")
	proto.RegisterType((*RemoveImageResponse)(nil), "msg.RemoveImageResponse")
	proto.RegisterType((*ResizeImageRequest)(nil), "msg.ResizeImageRequest")
	proto.RegisterType((*ResizeImageResponse)(nil), "msg.ResizeImageResponse")
	proto.RegisterType((*GetImageInfoRequest)(nil), "msg.GetImageInfoRequest")
	proto.RegisterType((*GetImageInfoResponse)(nil), "msg.GetImageInfoResponse")
	proto.RegisterType((*Request)(nil), "msg.Request")
	proto.RegisterType((*Response)(nil), "msg.Response")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 1905 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xcd, 0x6f, 0xe4, 0x48,
	0x15, 0x6f, 0xb7, 0x3b, 0x49, 0xe7, 0xf5, 0x97, 0xbb, 0xba, 0x33, 0xe9, 0xcd, 0x2e, 0x43, 0x30,
	0xd1, 0xec, 0x28, 0x5a, 0x22, 0x14, 0x58, 0xd8, 0x45, 0x48, 0x2b, 0x32, 0xc9, 0xa6, 0xa3, 0x59,
	0x92, 0xac, 0x07, 0xb8, 0x41, 0xcb, 0x69, 0xd7, 0x3a, 0x26, 0xdd, 0x2e, 0xe3, 0x72, 0x0f, 0x3b,
	0x23, 0x24, 0x24, 0x46, 0xdc, 0x10, 0x17, 0x24, 0xae, 0x48, 0x1c, 0xb8, 0xf1, 0x97, 0xf0, 0x4f,
	0xa1, 0x7a, 0x55, 0xae, 0x2e, 0x7f, 0x64, 0x46, 0x88, 0xc0, 0xcd, 0x55, 0xf5, 0xde, 0xaf, 0xde,
	0x57, 0xfd, 0xea, 0x95, 0xa1, 0xbf, 0xa4, 0x9c, 0xfb, 0x21, 0xe5, 0x47, 0x49, 0xca, 0x32, 0x46,
	0xec, 0x25, 0x0f, 0xdd, 0xbf, 0x58, 0x30, 0x7c, 0x96, 0x52, 0x3f, 0xa3, 0xd7, 0x8c, 0x2d, 0x3c,
	0xfa, 0x9b, 0x15, 0xe5, 0x19, 0x21, 0xd0, 0x8a, 0xfd, 0x25, 0x9d, 0x58, 0xfb, 0xd6, 0xd3, 0x6d,
	0x0f, 0xbf, 0xc9, 0x23, 0xd8, 0x4c, 0x42, 0x1e, 0xbd, 0xa6, 0x93, 0xe6, 0xbe, 0xf5, 0x74, 0xc3,
	0x53, 0x23, 0x32, 0x81, 0xad, 0x24, 0x9c, 0xb3, 0x55, 0x9c, 0x4d, 0x6c, 0x5c, 0xc8, 0x87, 0xe4,
	0x00, 0x7a, 0x5f, 0xf9, 0xd1, 0x62, 0x95, 0xd2, 0x80, 0x2d, 0xfd, 0x28, 0x9e, 0xb4, 0x10, 0xae,
	0x38, 0x29, 0xf6, 0x4a, 0x19, 0xcb, 0x26, 0x1b, 0x72, 0x2f, 0xf1, 0xed, 0xfe, 0x18, 0x88, 0x69,
	0x14, 0x4f, 0x58, 0xcc, 0x29, 0xe9, 0x43, 0x93, 0xdd, 0xa1, 0x4d, 0x6d, 0xaf, 0xc9, 0xee, 0xd0,
	0x22, 0xc6, 0x16, 0x51, 0xa0, 0x2d, 0xc2, 0x91, 0x4b, 0xc0, 0xf9, 0x22, 0xe2, 0x99, 0xd0, 0xe5,
	0xca, 0x23, 0xf7, 0xef, 0x16, 0xb4, 0x71, 0x39, 0xfe, 0x8a, 0x19, 0x8a, 0x96, 0xa9, 0xa8, 0xdd,
	0x6e, 0xd6, 0xba, 0x6d, 0xdf, 0xe7, 0x76, 0xeb, 0x1d, 0x6e, 0x6f, 0xbc, 0xcd, 0xed, 0x4d, 0xc3,
	0xed, 0x63, 0x18, 0x1a, 0x86, 0x2b, 0xaf, 0xbf, 0x01, 0xcd, 0x24, 0x9a, 0x58, 0xfb, 0xf6, 0xd3,
	0xce, 0x71, 0xef, 0x68, 0xc9, 0xc3, 0xa3, 0xdc, 0x0f, 0xaf, 0x99, 0x44, 0xee, 0x87, 0x30, 0x3c,
	0xa5, 0x0b, 0xfa, 0xce, 0xfc, 0xb9, 0x07, 0x40, 0x4c, 0xc1, 0xfa, 0x98, 0xba, 0x07, 0xd0, 0xff,
	0x49, 0x92, 0x2c, 0x5e, 0x5d, 0x9c, 0x1a, 0x58, 0xab, 0x95, 0x0a, 0xd5, 0xb6, 0x87, 0xdf, 0xee,
	0xc7, 0x30, 0xd0, 0x52, 0x0a, 0xa8, 0x46, 0x4c, 0x80, 0xeb, 0xe4, 0x34, 0xa3, 0xc0, 0xfd, 0xb3,
	0x05, 0x9d, 0x13, 0xc6, 0xb2, 0x1c, 0x7a, 0x07, 0x36, 0x19, 0x0f, 0x66, 0x3a, 0x0f, 0x1b, 0x8c,
	0x07, 0x17, 0x81, 0x86, 0x6a, 0x1a, 0x50, 0x04, 0x5a, 0x3a, 0x09, 0xb6, 0x87, 0xdf, 0x62, 0x2e,
	0x61, 0xa9, 0x8c, 0x7f, 0xcf, 0xc3, 0x6f, 0x91, 0x16, 0x3f, 0x08, 0x52, 0xca, 0xb9, 0x0a, 0x7b,
	0x3e, 0x14, 0xd2, 0xb7, 0x8c, 0xeb, 0x80, 0x8b, 0x6f, 0xf7, 0x0b, 0xd8, 0xbc, 0x3e, 0xbf, 0x10,
	0x25, 0x21, 0xb0, 0x42, 0x6d, 0x08, 0x7e, 0x0b, 0xac, 0x97, 0x34, 0xe5, 0x11, 0x8b, 0xd1, 0x14,
	0xdb, 0xcb, 0x87, 0x64, 0x0c, 0xc2, 0xd4, 0x28, 0x98, 0xd8, 0xfb, 0xb6, 0xb2, 0x3b, 0x0a, 0xdc,
	0x27, 0xb0, 0x25, 0xd1, 0x38, 0x79, 0xdf, 0x48, 0x5a, 0x07, 0x93, 0x26, 0x57, 0x30, 0x65, 0x7f,
	0xb3, 0x60, 0x70, 0x4e, 0xb3, 0xeb, 0xf0, 0xa7, 0x7e, 0x92, 0x87, 0xe2, 0x39, 0xf4, 0x44, 0x5a,
	0x67, 0x6a, 0x07, 0xae, 0x74, 0x9f, 0xa0, 0x6e, 0x49, 0xf8, 0x48, 0x64, 0xf0, 0x17, 0x4a, 0xf0,
	0x2c, 0xce, 0xd2, 0x57, 0x5e, 0x37, 0x31, 0xa6, 0xf6, 0x3e, 0x83, 0x61, 0x45, 0x84, 0x38, 0x60,
	0xdf, 0xd1, 0x57, 0xca, 0x41, 0xf1, 0x29, 0xbc, 0x78, 0xe9, 0x2f, 0x56, 0x54, 0x79, 0x27, 0x07,
	0x3f, 0x6a, 0x7e, 0x62, 0xb9, 0xff, 0xb0, 0xa0, 0x7f, 0xc5, 0x83, 0xd3, 0x57, 0xb1, 0xbf, 0x8c,
	0xe6, 0x18, 0x20, 0xed, 0xf2, 0x3a, 0x55, 0x32, 0x44, 0x79, 0xb8, 0x9b, 0x95, 0x70, 0x63, 0x72,
	0x6c, 0x15, 0x50, 0x91, 0x1c, 0x02, 0xad, 0x88, 0x2b, 0x1e, 0x68, 0x7b, 0xf8, 0x2d, 0xe7, 0x56,
	0x09, 0x66, 0x0b, 0xe7, 0x56, 0x09, 0x79, 0x0a, 0x83, 0x88, 0x27, 0x34, 0x0e, 0xa2, 0x38, 0x9c,
	0x23, 0x0f, 0x60, 0xd6, 0xda, 0x5e, 0x79, 0xda, 0xfd, 0x97, 0x0d, 0xce, 0x3a, 0x3a, 0xaa, 0x14,
	0x4f, 0x60, 0x9b, 0xa6, 0x29, 0x4b, 0xe7, 0x2c, 0xa0, 0x2a, 0x8e, 0x07, 0xa5, 0x38, 0x4a, 0xc9,
	0xa3, 0xb3, 0x5c, 0x4c, 0x46, 0x71, 0xad, 0x46, 0x7e, 0x05, 0x23, 0x49, 0x0a, 0xb3, 0x24, 0x5c,
	0xfa, 0xc9, 0xba, 0x0e, 0x04, 0xda, 0x77, 0xea, 0xd1, 0xae, 0x51, 0xe1, 0xda, 0x90, 0x97, 0xb0,
	0x24, 0xa9, 0x2c, 0x90, 0xef, 0x82, 0x9d, 0x84, 0x1c, 0xeb, 0xa7, 0x73, 0xfc, 0xf8, 0x1e, 0xbc,
	0x50, 0x65, 0x57, 0x88, 0xee, 0xfd, 0x0c, 0xfa, 0x45, 0x73, 0x6b, 0x32, 0xfa, 0x91, 0x99, 0xd1,
	0xfe, 0xf1, 0xa3, 0x02, 0x2e, 0x6a, 0x3f, 0x63, 0x01, 0x35, 0x32, 0xbd, 0x77, 0x06, 0xbb, 0xf7,
	0x98, 0xfd, 0x9f, 0x14, 0xcc, 0xde, 0x29, 0xb4, 0x73, 0x6b, 0x6b, 0xf4, 0x5c, 0x53, 0xaf, 0x73,
	0xdc, 0x35, 0x0e, 0x04, 0x37, 0xcb, 0xee, 0x1a, 0x93, 0x79, 0xc5, 0x03, 0xe3, 0x60, 0xd4, 0xd7,
	0xdd, 0x13, 0xe8, 0xcf, 0x57, 0x69, 0x4a, 0xe3, 0xac, 0x78, 0x42, 0x4b, 0xb3, 0xee, 0x5f, 0x2d,
	0x18, 0x1a, 0x90, 0xaa, 0x40, 0x8e, 0x8b, 0x05, 0x22, 0x42, 0x35, 0x46, 0x9b, 0xa4, 0xdc, 0x3a,
	0x50, 0x46, 0x41, 0x1c, 0x40, 0x8f, 0xf1, 0xa0, 0x50, 0x0a, 0x62, 0xc3, 0xe2, 0x24, 0xf9, 0x10,
	0x5a, 0x8c, 0x07, 0x79, 0x5e, 0x47, 0x39, 0xa8, 0x71, 0x90, 0x3c, 0x14, 0x70, 0xff, 0x68, 0xc1,
	0xf8, 0x9c, 0x66, 0xcf, 0x16, 0x2b, 0x9e, 0xd1, 0xd4, 0xf0, 0xf7, 0x07, 0xd0, 0x09, 0xd9, 0x72,
	0x96, 0xca, 0x21, 0x5a, 0xd7, 0x39, 0xde, 0xc9, 0x13, 0x59, 0x88, 0x8d, 0x07, 0x21, 0x5b, 0xe6,
	0x7a, 0x1f, 0x43, 0x27, 0x4c, 0xd6, 0x7a, 0x32, 0xd2, 0xe3, 0x3a, 0xfa, 0xf0, 0x20, 0x4c, 0x72,
	0x35, 0xf7, 0x4f, 0x16, 0xec, 0x94, 0xec, 0x50, 0x41, 0xfa, 0x14, 0xba, 0xd2, 0x10, 0x39, 0x56,
	0x96, 0x3c, 0x2a, 0x5b, 0x22, 0x57, 0xbd, 0x0e, 0x9a, 0xa2, 0x54, 0x3f, 0x81, 0xae, 0xb4, 0x45,
	0xa9, 0x36, 0x8b, 0x4e, 0x14, 0xaa, 0xdc, 0xeb, 0xa0, 0x35, 0x72, 0xe0, 0x3e, 0x86, 0xae, 0xbc,
	0x20, 0xee, 0xb9, 0x9e, 0xf6, 0x91, 0x97, 0x5e, 0x64, 0x4c, 0xc7, 0x4b, 0xde, 0x31, 0x96, 0xbe,
	0x63, 0xbe, 0x05, 0x03, 0x2d, 0x71, 0x0f, 0x88, 0x0b, 0xce, 0x94, 0xfa, 0x69, 0x76, 0x43, 0xfd,
	0xec, 0x3e, 0x98, 0x6f, 0xc3, 0xd0, 0x90, 0xb9, 0x07, 0xe8, 0x35, 0x6c, 0x5f, 0x2c, 0xfd, 0x90,
	0x22, 0x41, 0xee, 0xc9, 0x06, 0xc3, 0xb8, 0x77, 0xf5, 0x98, 0x7c, 0x00, 0xdb, 0x91, 0x10, 0x34,
	0xba, 0x8b, 0xf5, 0x44, 0xed, 0xdd, 0xf6, 0x4d, 0xe8, 0xb0, 0x9b, 0x5f, 0xd3, 0x79, 0x36, 0xc3,
	0xa5, 0x16, 0x2e, 0x81, 0x9c, 0x7a, 0x11, 0xbd, 0xa6, 0xee, 0x1b, 0x2b, 0xef, 0x91, 0xd0, 0x84,
	0xdc, 0x8f, 0xff, 0xb3, 0x15, 0xbf, 0x83, 0x51, 0xc1, 0x08, 0x15, 0xa8, 0x1f, 0x56, 0x0f, 0xd8,
	0x7b, 0x98, 0x7d, 0x43, 0xb8, 0xf6, 0x94, 0x7d, 0x64, 0x44, 0x54, 0x95, 0x4d, 0x1f, 0x15, 0xf5,
	0xac, 0xb7, 0x16, 0x70, 0x2f, 0x81, 0x78, 0x74, 0xc9, 0x5e, 0x3e, 0x50, 0x08, 0x84, 0x37, 0x05,
	0xbc, 0x77, 0x79, 0x63, 0x08, 0x3f, 0x80, 0x37, 0x37, 0xc2, 0x1b, 0x11, 0xe7, 0xff, 0x5d, 0x42,
	0xa5, 0x87, 0xc6, 0x1e, 0xef, 0xf6, 0x50, 0x0b, 0x3f, 0x80, 0x87, 0x57, 0x30, 0x3a, 0xa7, 0xd9,
	0x7a, 0xe9, 0xbf, 0x4e, 0xd8, 0x6b, 0x24, 0x51, 0x03, 0x50, 0xf9, 0xf3, 0xfd, 0xaa, 0x3f, 0x9a,
	0xb8, 0x1e, 0xca, 0x99, 0x3f, 0xb4, 0x61, 0x6b, 0x4d, 0xbe, 0xdd, 0x1b, 0xc6, 0xb2, 0x12, 0x6b,
	0x3b, 0xa8, 0x6c, 0x34, 0xbc, 0xd3, 0x86, 0xd7, 0xb9, 0x31, 0xfa, 0xdf, 0xcf, 0xc0, 0x11, 0xfd,
	0x2f, 0xcf, 0x58, 0x52, 0x22, 0x6e, 0x7d, 0x73, 0x18, 0x54, 0x37, 0x6d, 0x78, 0x7d, 0x56, 0x24,
	0xbf, 0x53, 0x18, 0xde, 0xe6, 0x2c, 0xa5, 0x11, 0x6c, 0x83, 0x6d, 0xcb, 0x3c, 0x37, 0x6d, 0x78,
	0xce, 0x6d, 0x99, 0xfb, 0xce, 0x80, 0x84, 0x34, 0x9b, 0xc9, 0x9b, 0x4c, 0xc3, 0xb4, 0xde, 0x72,
	0xf3, 0x08, 0x98, 0x10, 0xe7, 0x96, 0xeb, 0x9b, 0xeb, 0x0c, 0xc8, 0x22, 0xe2, 0xd9, 0x4c, 0xe4,
	0x8e, 0x6b, 0x98, 0x0d, 0x03, 0xa6, 0xfc, 0x2a, 0x13, 0x30, 0x8b, 0xd2, 0x9c, 0x08, 0x8a, 0x2f,
	0xde, 0x16, 0xb3, 0x28, 0xd0, 0x20, 0x9b, 0x46, 0x50, 0x8a, 0xcf, 0x13, 0x11, 0x14, 0x14, 0xbf,
	0x08, 0x72, 0x80, 0x29, 0x8c, 0x64, 0x77, 0x88, 0x96, 0x68, 0x8c, 0x2d, 0xe3, 0xfe, 0xaa, 0xbc,
	0x78, 0xa7, 0x0d, 0x6f, 0x38, 0xaf, 0x3c, 0x83, 0x4f, 0x60, 0x28, 0x02, 0x83, 0x1d, 0xa0, 0xc6,
	0x69, 0xdf, 0x7f, 0xb3, 0x4e, 0x1b, 0xde, 0x20, 0x14, 0x53, 0x46, 0x54, 0xa6, 0x30, 0x0a, 0xf0,
	0xd9, 0x55, 0xb4, 0x66, 0xdb, 0xb0, 0xa6, 0xf2, 0x7e, 0x13, 0xd6, 0x04, 0x95, 0x47, 0x9d, 0x07,
	0xbb, 0xc2, 0x9a, 0xb9, 0xbc, 0xaa, 0x67, 0xa6, 0x4d, 0x80, 0x68, 0xef, 0xe5, 0x36, 0x55, 0xba,
	0x8a, 0x69, 0xc3, 0x1b, 0x87, 0x75, 0xdd, 0xc6, 0x73, 0x18, 0xab, 0x58, 0xe1, 0xa1, 0xd2, 0x80,
	0x1d, 0x04, 0xdc, 0x2d, 0x73, 0xf6, 0x1a, 0x8e, 0xcc, 0xab, 0x77, 0xcf, 0x73, 0x18, 0xa7, 0xc8,
	0x88, 0x25, 0xb0, 0xae, 0x01, 0x56, 0xe5, 0x6b, 0x01, 0x96, 0x56, 0x59, 0x1c, 0xc1, 0x04, 0xf9,
	0x94, 0xc0, 0x7a, 0x05, 0xb0, 0x32, 0x5d, 0x4a, 0xb0, 0x0a, 0x89, 0x5e, 0xc2, 0x8e, 0x08, 0x9d,
	0x3e, 0xbc, 0x33, 0xb5, 0x30, 0xe9, 0x23, 0xda, 0xa4, 0xc0, 0x0d, 0x06, 0x35, 0x4d, 0x1b, 0xde,
	0x28, 0xac, 0x4e, 0x9f, 0x6c, 0xc1, 0xc6, 0x2a, 0x16, 0xfd, 0xe5, 0x3f, 0xdb, 0xd0, 0x36, 0xda,
	0x9e, 0x9e, 0x62, 0x81, 0x42, 0xcb, 0x34, 0x34, 0x68, 0x40, 0x2e, 0x4c, 0x1b, 0x5e, 0xf7, 0xc6,
	0x6c, 0x73, 0x4e, 0x60, 0x68, 0x10, 0x41, 0xa1, 0x6b, 0x1a, 0x17, 0x99, 0x40, 0x03, 0x0c, 0x58,
	0xa9, 0xcb, 0x39, 0x07, 0x62, 0x72, 0x81, 0x02, 0xb1, 0x8d, 0x3a, 0xab, 0x34, 0x34, 0xa2, 0xce,
	0x6e, 0x2b, 0x5d, 0xce, 0x14, 0x46, 0x05, 0x3a, 0x50, 0x48, 0xad, 0xb7, 0xf5, 0x7f, 0x02, 0xc9,
	0x20, 0x84, 0x35, 0x52, 0x81, 0x11, 0x14, 0xd2, 0x86, 0x81, 0x54, 0xf9, 0xdf, 0x21, 0x90, 0x16,
	0x95, 0x9f, 0x20, 0x27, 0x30, 0x34, 0x48, 0x41, 0xe1, 0x6c, 0x1a, 0x01, 0x2a, 0xfd, 0x8e, 0x10,
	0x01, 0xd2, 0xb4, 0xa0, 0x30, 0xd6, 0xb5, 0xae, 0x4e, 0xa2, 0x82, 0xd9, 0xaa, 0xd4, 0xba, 0xf9,
	0x87, 0x64, 0x5d, 0xeb, 0x85, 0xff, 0x26, 0x8a, 0x33, 0x73, 0x6a, 0x50, 0x50, 0xed, 0xb7, 0x34,
	0xba, 0x8a, 0x33, 0x15, 0x39, 0xac, 0x6d, 0x2a, 0xb2, 0x83, 0x02, 0xda, 0x36, 0x6c, 0xaa, 0xfe,
	0xb5, 0x11, 0x36, 0x05, 0xd5, 0x7f, 0x39, 0x3f, 0x87, 0x49, 0x95, 0x20, 0x14, 0xa0, 0x64, 0x88,
	0xbd, 0x3a, 0x86, 0xd0, 0x98, 0x3b, 0x61, 0xed, 0x43, 0xe0, 0x12, 0x76, 0x4a, 0x1c, 0xa1, 0x30,
	0x3b, 0xc6, 0xe1, 0xa9, 0xe9, 0x02, 0xc5, 0xe1, 0x99, 0xd7, 0x34, 0x87, 0x97, 0xb0, 0x53, 0xa2,
	0x09, 0x85, 0xd7, 0x35, 0xf0, 0x6a, 0xfa, 0x30, 0x81, 0x97, 0xd6, 0xb4, 0x67, 0x88, 0x57, 0x60,
	0x0a, 0x85, 0xd7, 0x2b, 0xe0, 0x55, 0xba, 0x1e, 0x89, 0x57, 0x6d, 0x86, 0xbe, 0x84, 0x47, 0x22,
	0x8c, 0x91, 0x26, 0x0b, 0x0d, 0xd8, 0x2f, 0xd2, 0x6c, 0xa5, 0xef, 0x50, 0x34, 0x5b, 0x99, 0xd7,
	0x7c, 0x71, 0x98, 0xe0, 0x73, 0xb4, 0xf8, 0x1c, 0x27, 0x7d, 0x80, 0x44, 0xcc, 0x88, 0x53, 0x75,
	0xe7, 0x34, 0xc8, 0x07, 0x30, 0xc1, 0xf1, 0x7c, 0x11, 0xd1, 0x38, 0x53, 0x7f, 0x71, 0xa6, 0x51,
	0x78, 0x4b, 0x53, 0xc7, 0x22, 0xbb, 0x30, 0xba, 0x96, 0xab, 0x98, 0xa9, 0x4b, 0x86, 0x27, 0xc5,
	0x69, 0x92, 0x31, 0x38, 0xb8, 0xf0, 0xc2, 0x5f, 0x52, 0xa5, 0xe4, 0xd8, 0x87, 0xbf, 0xc4, 0xf7,
	0x50, 0x61, 0xbf, 0x4d, 0xf1, 0x8c, 0x71, 0x1a, 0x02, 0xa9, 0x7e, 0x8b, 0x09, 0x8c, 0x0b, 0x0b,
	0x17, 0xf1, 0x4b, 0x7f, 0x11, 0x05, 0x4e, 0x93, 0x0c, 0xa0, 0x13, 0xb3, 0x2b, 0x1e, 0xf0, 0xb3,
	0xaf, 0x23, 0x9e, 0x39, 0xf6, 0xe1, 0xef, 0x61, 0x5c, 0xd7, 0xd3, 0x93, 0x21, 0xf4, 0x8c, 0xdc,
	0xa3, 0x5b, 0x03, 0xe8, 0x60, 0x4c, 0x51, 0x95, 0x3b, 0x16, 0x19, 0xc1, 0x60, 0x15, 0xdf, 0xc5,
	0xec, 0xb7, 0xb1, 0x70, 0xe1, 0xd2, 0x5f, 0x52, 0xa7, 0x29, 0x9c, 0x5f, 0xfa, 0x29, 0xbf, 0xf5,
	0x17, 0xa8, 0xf9, 0x8c, 0xc5, 0x19, 0xfd, 0x3a, 0x43, 0x60, 0xc7, 0x26, 0x0e, 0x74, 0x93, 0x55,
	0x76, 0x96, 0xcd, 0x03, 0x39, 0xd3, 0x3a, 0xfc, 0x12, 0xc6, 0x75, 0x6d, 0xb8, 0x30, 0xc0, 0x28,
	0x16, 0x34, 0x60, 0x08, 0x3d, 0x34, 0xe0, 0x92, 0x65, 0x9f, 0xb3, 0x55, 0x1c, 0x48, 0x13, 0x0c,
	0xa9, 0xcf, 0xfd, 0x68, 0xe1, 0x34, 0x0f, 0xdf, 0x58, 0x02, 0xb3, 0xda, 0xf8, 0x4a, 0x4c, 0x3d,
	0x7f, 0xa5, 0x62, 0x68, 0x4c, 0x19, 0xc8, 0x2e, 0x3c, 0x56, 0x7e, 0x18, 0x50, 0x05, 0x6f, 0x9a,
	0xe4, 0x7d, 0xd8, 0x4d, 0x56, 0x99, 0xb9, 0x95, 0x76, 0xcc, 0x3e, 0xfc, 0x14, 0x4b, 0xa5, 0x64,
	0x41, 0x1f, 0x20, 0x2f, 0x30, 0xdc, 0x7e, 0x0c, 0x4e, 0x3e, 0x5e, 0xef, 0x7d, 0xb3, 0x89, 0x3f,
	0xf8, 0xbf, 0xf7, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55, 0x05, 0x90, 0x4e, 0xf2, 0x17, 0x00,
	0x00,
}
