- hosts:
  - monitors
  - osds
  - clients

  gather_facts: false 
  any_errors_fatal: true
  become: true
  tags: always

  vars:
    delegate_facts_host: True 

  pre_tasks:
    - import_role:
        name: fastblock-defaults

    # If we can't get python2 installed before any module is used we will fail
    # so just try what we can to get it installed
    - import_tasks: raw_install_python.yml

    - name: gather facts
      setup:
        gather_subset:
          - 'all'
          - '!facter'
          - '!ohai'
      when:
        - not delegate_facts_host | bool or inventory_hostname in groups.get(client_group_name, [])

    - name: gather and delegate facts
      setup:
        gather_subset:
          - 'all'
          - '!facter'
          - '!ohai'
      delegate_to: "{{ item }}"
      delegate_facts: True
      with_items: "{{ groups['all'] | difference(groups.get('clients', [])) }}"
      run_once: true
      when: delegate_facts_host | bool

  tasks:
    - import_role:
        name: fastblock-facts
    - import_role:
        name: fastblock-common
    - import_role:
        name: fastblock-config

- hosts: monitors
  gather_facts: false
  become: True
  any_errors_fatal: true
  pre_tasks:
    - name: set fastblock monitor install 'In Progress'
      run_once: true
      set_stats:
        data:
          installer_phase_fastblock_mon:
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

  tasks:
    - import_role:
        name: fastblock-defaults
      tags: ['fastblock_update_config']
    - import_role:
        name: fastblock-config
      tags: ['fastblock_update_config']
    - import_role:
        name: fastblock-monitor

  post_tasks:
    - name: set fastblock monitor install 'Complete'
      run_once: true
      set_stats:
        data:
          installer_phase_fastblock_mon:
            status: "Complete"
            end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- hosts: osds
  gather_facts: false
  become: True
  any_errors_fatal: true
  pre_tasks:
    - name: set fastblock osd install 'In Progress'
      run_once: true
      set_stats:
        data:
          installer_phase_fastblock_osd:
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

  tasks:
    - import_role:
        name: fastblock-defaults
      tags: ['fastblock_update_config']
    - import_role:
        name: fastblock-facts
      tags: ['fastblock_update_config']
    - import_role:
        name: fastblock-config
      tags: ['fastblock_update_config']
    - import_role:
        name: fastblock-osd

  post_tasks:
    - name: set fastblock osd install 'Complete'
      run_once: true
      set_stats:
        data:
          installer_phase_fastblock_osd:
            status: "Complete"
            end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- hosts: clients
  gather_facts: false
  become: True
  any_errors_fatal: true
  tags: 'fastblock_client'
  pre_tasks:
    - name: set fastblock client install 'In Progress'
      run_once: true
      set_stats:
        data:
          installer_phase_fastblock_client:
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

  tasks:
    - import_role:
        name: fastblock-defaults
      tags: ['fastblock_update_config']
    - import_role:
        name: fastblock-facts
      tags: ['fastblock_update_config']
    - import_role:
        name: fastblock-config
      tags: ['fastblock_update_config']

  post_tasks:
    - name: set fastblock client install 'Complete'
      run_once: true
      set_stats:
        data:
          installer_phase_fastblock_client:
            status: "Complete"
            end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"