etcd_server = ["127.0.0.1:2379"] # Your etcd servers.
etcd_name = "monitor1"
etcd_initial_cluster = "monitor1=http://<host ip>:2380"
etcd_advertise_client_urls = ["http://<host ip>:2379"]
etcd_advertise_peer_urls = ["http://<host ip>:2380"]
etcd_listen_peer_urls = ["http://<host ip>:2380"]
etcd_listen_client_urls = ["http://localhost:2379", "http://<host ip>:2379"]
data_dir = "/tmp/monitor"
election_master_key = "fastblock_master"
hostname="monitor1"
port=1111
prometheus_port=1112
log_path = "/var/log/fastblock/monitor1.log"
log_level = "info"
